In [1]:
import matplotlib.pyplot as plt
#import numpy as np
import pandas as pd
import os
import shutil
import re
import seaborn as sns
from itertools import combinations
import numpy as np
from pymatgen.core.structure import Structure

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
#Done
def get_elneg(atom_type):
    from pymatgen.core.periodic_table import Element

    # Example: Get electronegativity of Oxygen
    elneg = Element(atom_type).X
    return elneg

In [5]:
#Done
def vasp_to_coordinate(coord_line, cell_matrix, atom_type, fractional =False):
    coord_list = coord_line.split()[0:3]
    #atom_type = coord_line.split()[0]
    for n in range(len(coord_list)):
        #coord_list[n] = re.sub("d","0",coord_list[n])
        coord_list[n] = float(coord_list[n])
    coord_array = np.array(coord_list).reshape(1,3)
    if fractional == False:
        coord_array_ang = np.dot(coord_array,cell_matrix)
        return (atom_type,coord_array_ang) 
    else:
        return (atom_type,coord_array)

In [6]:
#Done
decimal = 4
def TOTEN_vasp(outcar_path, decimal = decimal):
    outcar = open(outcar_path, 'r')
    outcar_lines = outcar.readlines()
    for n_line in range(len(outcar_lines)):
        if 'TOTEN' in outcar_lines[n_line]:
            TOTEN = round(float(outcar_lines[n_line].split()[4]),decimal)
    return TOTEN

In [7]:
#Done
def countX(lst, x):
    count = 0
    for ele in lst:
        if (ele == x):
            count = count + 1
    return count

In [8]:
#Done
def two_atoms_dist(atom1_coord, atom2_coord, decimal = decimal):
    return round(np.linalg.norm(atom1_coord - atom2_coord),decimal)

In [9]:
#Done
def find_element(list_, line):
    final_result = False
    for element in list_:
        if element in line:
            result = True
        else:
            result = False
        final_result = final_result or result
    return final_result

# INCAR Files

In [10]:
from pymatgen.io.vasp.inputs import Potcar

def get_valence_electrons_from_potcar_pymatgen(potcar_file):
    """
    Reads a POTCAR file using pymatgen and extracts the number of valence electrons for each element.

    Args:
        potcar_file (str): Path to the POTCAR file.

    Returns:
        dict: A dictionary where keys are element names and values are the number of valence electrons.
    """
    try:
        # Use pymatgen's Potcar class to parse the POTCAR file
        potcar = Potcar.from_file(potcar_file)
        
        # Extract element names and their ZVAL values
        valence_electrons = {entry.element: entry.nelectrons for entry in potcar}
        
        return valence_electrons
    except FileNotFoundError:
        raise FileNotFoundError(f"The file {potcar_file} does not exist.")
    except Exception as e:
        raise RuntimeError(f"An error occurred while parsing the POTCAR file: {e}")

In [11]:
#test
valence_electrons = get_valence_electrons_from_potcar_pymatgen('./test_repeat_structure/0_VASP/SDA_test/0_test/POTCAR.surf')
valence_electrons

{'Co': 9.0, 'Ni': 10.0}

In [12]:
#Done

#In this script since we are working mainly with ACF.dat file, it works for all different versions of POSCAR 
#and qs_input files. 
# For vasp inputs you can use get_valence_electrons_from_pymatgen function to create the dictionary 
#for valence electrons


valence_electrons = {'Ag':19.0,
                     'Au':11.0,
                     'Co':9.0,
                     'Fe':16.0,
                     'Ru':16.0,
                     'Pd':16.0,
                     'Pt':16.0,
                     'Cu':19.0,
                     'Ni':10.0,
                      'N':5.0,
                      'H':1}

def bader_df(acf_dat, #path to the acf.dat file
             input_path, #path to the input file
             input_type = 'qs', #'vasp' or 'qs'
             valence_dict = valence_electrons, #dictionary which lists the valence electrons
             slab = True, #if the structure is slab or bulk to specify surface atoms
             atom_types_line_num = 5,  #The line number in 'POSCAR' which specify the atom types
             type_num_line_num = 6, #The line number in 'POSCAR' which specify the number of atoms for each type
             z_threshhold = 1.0, #What is the maximum value of difference between the z parameter of surface layers for example they are all in range 14.5, 15,5 
             moleclue_exist = False,
             num_atom_mol = 2):

    acf_file = open(acf_dat, 'r')
    acf_lines = acf_file.readlines()[2:-4]
    
    acf_file.close()
    col_names=['#','x','y','z','Charge','Min_dist','atomic_volume']
    acf_df = pd.DataFrame()
    for i in range(len(col_names)):
        acf_df[col_names[i]] = [float(re.findall(r'-*\d+\.*\d*', line.split()[i])[0]) for line in acf_lines]
    acf_df.drop('#',axis=1,inplace=True)
    
    input_file = open(input_path, 'r')
    input_file_lines = input_file.readlines() 
    input_file.close()
    if input_type == 'qs':
        for line_num in range(len(input_file_lines)):
            line = input_file_lines[line_num]
            if 'nat' in line:
                nat = int(re.findall(r'\d+', line)[0])
            if 'ATOMIC_POSITIONS' in line:
                start_coord = line_num + 1
                #end_coord = start_coord + nat
                break
        end_coord = start_coord + nat
        coordinate_lines = input_file_lines[start_coord: end_coord] 
        atoms_list = []
        Zs = list(acf_df['z'])
        #Zs = []
        for line in coordinate_lines:
            atom_type = line.split()[0]
        #    z = line.split()[3]
        #    z_float = float(re.sub("d","0",z))
            atoms_list.append(atom_type)
        #    Zs.append(z_float)
        acf_df['z_alat'] = Zs
        #print(acf_df['z_alat'])
        if moleclue_exist == True:
            z_max = sorted(Zs,reverse = True)[num_atom_mol]
        elif moleclue_exist == False:
            z_max = sorted(Zs,reverse = True)[0]
        #print(z_max)
        
            
        
    elif input_type == 'vasp':
        atom_types = input_file_lines[atom_types_line_num].split()
        type_num = [int(i) for i in input_file_lines[type_num_line_num].split()]
        atoms_list = ''
        for i in range(0,len(atom_types)):
            atoms_list = atoms_list + type_num[i] * (atom_types[i] + ' ')
        atoms_list = atoms_list.split()
        Zs = list(acf_df['z'])
        acf_df['z_alat'] = Zs
        if moleclue_exist == True:
            z_max = sorted(Zs,reverse = True)[num_atom_mol]
        elif moleclue_exist == False:
            z_max = sorted(Zs,reverse = True)[0]
        #print(z_max)
    
    #diff_z = [abs(i-z_max) for i in Zs]    
    #for i in diff_z:
        #print(i)          
        
        
    
    acf_df['atom_type'] = atoms_list
    #print(atoms_list)
    acf_df = acf_df[['atom_type','x', 'y', 'z', 'Charge', 'Min_dist', 'atomic_volume','z_alat']]
    
    if slab == True:
        acf_df['surface_atom'] = np.where(acf_df['z_alat'] > z_max - z_threshhold,1,0)
        
    acf_df.drop('z_alat',axis=1,inplace=True)    
    valence_list = [valence_dict.get(i) for i in atoms_list] 
    acf_df['bader_charge'] = valence_list - acf_df['Charge']
    #acf_df.index = acf_df.index + 1
    
    return acf_df
    
#bader_df(acf_dat = '0_test_bader/ACF_original.dat', 
         #input_type = 'vasp',
         #input_path = '0_test_bader/CONTCAR')        
    
        
        
        
            
        
#This script has a problem it is not worked on vasp input when molecule exists, only qs is fixed for
#that condition, you have to consider adding exactly the same z_alat column using vasp poscar.

In [13]:
#Test qs
bader_df('./0_test_bader/ACF_original.dat', 
         './0_test_bader/input.in',
             input_type = 'qs',
             valence_dict = valence_electrons,
             slab = True,
             atom_types_line_num = 5, 
             type_num_line_num = 6,
             z_threshhold = 1.0)

   atom_type        x        y        z   Charge  Min_dist  atomic_volume  surface_atom  bader_charge
0         Cu  19.2343   0.0253   4.1746  19.0128    2.0694       380.7495             0       -0.0128
1         Ni   4.7013   0.0458   4.2969  18.0627    2.0256       305.6438             0       -8.0627
2         Cu  -0.0882  16.7327   4.1029  19.0112    2.1353       414.8718             0       -0.0112
3         Cu  14.3793   0.0475   4.0921  19.0160    2.1208       425.2662             0       -0.0160
4         Ni  16.7295   4.3127   4.2657  18.0381    2.0000       344.0589             0       -8.0381
5         Cu   2.2743   4.1930   4.1869  19.0169    2.0806       387.9776             0       -0.0169
6         Cu   7.2148   4.1865   4.1348  19.0099    2.0975       419.0325             0       -0.0099
7         Ni  12.0526   4.3116   4.2890  18.0440    2.0641       326.5942             0       -8.0440
8         Ni  14.4146   8.3093   4.2828  18.0256    2.0810       337.6821             0       -8.0256
9         Ni  -0.1948   8.4080   4.2813  18.0561    2.0167       331.3676             0       -8.0561
10        Cu   4.7360   8.3984   4.1686  19.0139    2.0693       393.6096             0       -0.0139
11        Ni   9.6520   8.3062   4.3314  18.0470    2.0099       308.7148             0       -8.0470
12        Cu  12.0007  12.5191   4.1511  19.0047    2.0668       403.0134             0       -0.0047
13        Cu  -2.5261  12.5281   4.1192  19.0261    2.1164       416.6806             0       -0.0261
14        Ni   2.2815  12.5139   4.2180  18.0632    2.0777       340.8154             0       -8.0632
15        Cu   7.1629  12.5087   4.1578  19.0147    2.0614       387.6840             0       -0.0147
16        Ni   2.3499   1.3326   8.0204  18.0016    2.0053        76.1110             0       -8.0016
17        Cu   7.1759   1.4012   7.9670  18.9593    2.0716        75.6083             0        0.0407
18        Cu  11.9855   1.4454   7.9646  18.9560    2.0836        76.7201             0        0.0440
19        Cu  16.8521   1.4151   7.9642  18.9560    2.0637        76.4596             0        0.0440
20        Cu  -0.0834   5.5520   8.0012  18.9565    2.0647        75.1020             0        0.0435
21        Cu   4.8008   5.5585   7.9650  18.9387    2.0852        76.0706             0        0.0613
22        Ni   9.6142   5.6065   8.0013  18.0063    2.0052        75.4359             0       -8.0063
23        Ni  14.4175   5.6263   7.9717  17.9758    1.9671        74.2508             0       -7.9758
24        Ni  -2.5149   9.7020   8.0056  17.9815    1.9745        74.8452             0       -7.9815
25        Cu   2.3237   9.7621   7.9593  18.9496    2.0521        75.6707             0        0.0504
26        Ni   7.2857   9.7201   7.9913  18.0007    1.9774        76.3422             0       -8.0007
27        Cu  12.0326   9.7845   8.0356  18.9494    2.0300        73.7701             0        0.0506
28        Cu  -4.9078  13.9273   7.9694  18.9498    2.0563        74.8378             0        0.0502
29        Cu  -0.1165  13.9082   7.9401  18.9571    2.0287        76.3532             0        0.0429
30        Cu   4.7730  13.9318   7.9098  18.9655    2.0580        77.2888             0        0.0345
31        Ni   9.6219  13.9030   7.9792  17.9957    2.0410        76.2798             0       -7.9957
32        Ni  -0.0011   2.7865  11.7790  17.9972    2.0519        75.7955             0       -7.9972
33        Ni   4.7274   2.7334  11.7545  17.9675    1.9847        74.2251             0       -7.9675
34        Ni   9.4831   2.8232  11.7579  17.9872    1.9992        74.9406             0       -7.9872
35        Cu  14.4148   2.8796  11.7451  18.9355    2.0599        76.7054             0        0.0645
36        Ni  -2.4904   7.0235  11.7445  17.9921    2.0732        76.0743             0       -7.9921
37        Cu   2.3351   6.9713  11.7410  18.9542    2.0843        75.1424             0        0.0458
38        Ni   7.1930   6.9580  11.7435  17.9779    2.0045        75.1387             0       -7.9779
39        Cu  11.9966   6.9976  11.7883  18.9575    2.0788        75.2928             0        0.0425
40        Ni  -4.8596  11.2054  11.7828  17.9882    2.0752        75.3699             0       -7.9882
41        Ni  -0.1959  11.1445  11.7499  17.9925    1.9769        75.1130             0       -7.9925
42        Cu   4.7572  11.1254  11.6911  18.9602    2.0157        75.3772             0        0.0398
43        Ni   9.5874  11.1896  11.7641  17.9828    1.9734        75.7331             0       -7.9828
44        Ni  -7.3165  15.3482  11.7325  17.9943    1.9886        75.1387             0       -7.9943
45        Ni  -2.5641  15.3549  11.7862  17.9824    2.0467        74.7424             0       -7.9824
46        Cu   2.2376  15.3187  11.6941  18.9178    2.0361        75.9973             0        0.0822
47        Cu   7.2238  15.3253  11.6954  18.9209    1.9825        75.1681             0        0.0791
48        Ni   0.0203   0.0208  15.4232  17.9872    2.0265       288.9312             1       -7.9872
49        Cu  -4.9167  16.7267  15.6194  18.9977    2.0980       447.4567             1        0.0023
50        Ni   9.4412   0.0460  15.4373  17.9861    2.0327       308.6671             1       -7.9861
51        Au   4.7337  16.6866  15.8213  11.4458    2.4293       653.7020             1       -0.4458
52        Cu  -2.4166   4.2498  15.5724  18.9803    2.0861       371.8337             1        0.0197
53        Ni   2.4254   4.1551  15.4340  18.0148    2.0270       331.3162             1       -8.0148
54        Ni   7.1085   4.1952  15.3930  18.0285    1.9972       306.8032             1       -8.0285
55        Ni  11.7802   4.1548  15.4733  17.9888    2.0285       319.0542             1       -7.9888
56        Cu  14.4161   8.3673  15.5657  19.0158    2.1021       390.1533             1       -0.0158
57        Cu  -0.0262   8.3542  15.5783  18.9981    2.1015       413.4629             1        0.0019
58        Ni   4.7862   8.3325  15.4535  18.0350    2.0679       350.4687             1       -8.0350
59        Cu   9.5469   8.3490  15.6018  19.0033    2.0947       423.7876             1       -0.0033
60        Cu  12.0008  12.5569  15.5612  19.0132    2.0923       391.9658             1       -0.0132
61        Ni  -2.3766  12.6149  15.4103  18.0315    1.9706       315.9319             1       -8.0315
62        Ni   2.3055  12.3902  15.4203  17.9944    2.0663       308.3442             1       -7.9944
63        Ni   7.1684  12.4191  15.4332  18.0088    2.0142       302.5691             1       -8.0088

In [14]:
#test vasp
input_path = './test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.surf'
acf_dat = './test_repeat_structure/0_VASP/SDA_test/0_test/ACF.dat'
bader_df(acf_dat,
         input_path,
         input_type = 'vasp',
         valence_dict = valence_electrons,
         slab = True,
         atom_types_line_num = 5, 
         type_num_line_num = 6,
         z_threshhold = 1.0)

   atom_type       x       y       z   Charge  Min_dist  atomic_volume  surface_atom  bader_charge
0         Co  0.6309  1.7728  1.8977   8.9813    1.0668        48.3972             0        0.0187
1         Co  3.0651  1.7728  1.8977   8.9677    1.0504        49.6328             0        0.0323
2         Co  5.5664  1.7728  1.8977   8.9813    1.0668        48.3972             0        0.0187
3         Co  8.0006  1.7728  1.8977   8.9677    1.0504        49.6328             0        0.0323
4         Co -0.6197  3.9390  1.8977   8.9778    1.0512        48.4449             0        0.0222
5         Co  4.3157  3.9390  1.8977   8.9778    1.0512        48.4449             0        0.0222
6         Co -1.8368  6.0471  1.8977   8.9813    1.0668        48.3972             0        0.0187
7         Co  0.5974  6.0471  1.8977   8.9677    1.0504        49.6328             0        0.0323
8         Co  3.0987  6.0471  1.8977   8.9813    1.0668        48.3972             0        0.0187
9         Co  5.5328  6.0471  1.8977   8.9677    1.0504        49.6328             0        0.0323
10        Co -3.0874  8.2132  1.8977   8.9778    1.0512        48.4449             0        0.0222
11        Co  1.8480  8.2132  1.8977   8.9778    1.0512        48.4449             0        0.0222
12        Co  0.6285  0.3661  3.8820   8.9151    1.0380        10.5198             0        0.0849
13        Co  3.0675  0.3661  3.8820   8.9318    1.0486        10.5748             0        0.0682
14        Co  5.5640  0.3661  3.8820   8.9151    1.0380        10.5198             0        0.0849
15        Co  8.0030  0.3661  3.8820   8.9318    1.0486        10.5748             0        0.0682
16        Co  1.8480  2.4783  3.8820   8.9158    1.0400        10.5214             0        0.0842
17        Co  6.7835  2.4783  3.8820   8.9158    1.0400        10.5214             0        0.0842
18        Co -1.8392  4.6403  3.8820   8.9151    1.0380        10.5198             0        0.0849
19        Co  0.5998  4.6403  3.8820   8.9318    1.0486        10.5748             0        0.0682
20        Co  3.0962  4.6403  3.8820   8.9151    1.0380        10.5198             0        0.0849
21        Co  5.5352  4.6403  3.8820   8.9318    1.0486        10.5748             0        0.0682
22        Co -0.6197  6.7525  3.8820   8.9158    1.0400        10.5214             0        0.0842
23        Co  4.3157  6.7525  3.8820   8.9158    1.0400        10.5214             0        0.0842
24        Co  0.6285  1.7742  5.9618   8.9298    1.0331        10.5699             0        0.0702
25        Co  3.0675  1.7742  5.9618   8.9147    1.0538        10.5190             0        0.0853
26        Co  5.5640  1.7742  5.9618   8.9298    1.0331        10.5699             0        0.0702
27        Co  8.0030  1.7742  5.9618   8.9147    1.0538        10.5190             0        0.0853
28        Co -0.6197  3.9362  5.9618   8.9196    1.0545        10.5303             0        0.0804
29        Co  4.3157  3.9362  5.9618   8.9196    1.0545        10.5303             0        0.0804
30        Co -1.8392  6.0485  5.9618   8.9298    1.0331        10.5699             0        0.0702
31        Co  0.5998  6.0485  5.9618   8.9147    1.0538        10.5190             0        0.0853
32        Co  3.0962  6.0485  5.9618   8.9298    1.0331        10.5699             0        0.0702
33        Co  5.5352  6.0485  5.9618   8.9147    1.0538        10.5190             0        0.0853
34        Co -3.0874  8.2104  5.9618   8.9196    1.0545        10.5303             0        0.0804
35        Co  1.8480  8.2104  5.9618   8.9196    1.0545        10.5303             0        0.0804
36        Co  0.6309  0.3675  7.9461   8.9689    1.0696        49.6942             1        0.0311
37        Co  3.0651  0.3675  7.9461   8.9827    1.0773        48.0244             1        0.0173
38        Co  5.5664  0.3675  7.9461   8.9689    1.0696        49.6942             1        0.0311
39        Co  8.0006  0.3675  7.9461   8.9827    1.0773        48.0244             1        0.0173
40        Co  1.8480  2.4755  7.9461   8.9729    1.0666        48.2548             1        0.0271
41        Co  6.7835  2.4755  7.9461   8.9729    1.0666        48.2548             1        0.0271
42        Co -1.8368  4.6417  7.9461   8.9689    1.0696        49.6942             1        0.0311
43        Co  0.5974  4.6417  7.9461   8.9827    1.0773        48.0244             1        0.0173
44        Co  3.0986  4.6417  7.9461   8.9689    1.0696        49.6942             1        0.0311
45        Co  5.5328  4.6417  7.9461   8.9827    1.0773        48.0244             1        0.0173
46        Co -0.6197  6.7498  7.9461   8.9729    1.0666        48.2548             1        0.0271
47        Co  4.3157  6.7498  7.9461   8.9729    1.0666        48.2548             1        0.0271
48        Ni  1.8480  3.9196  1.8756  10.1705    1.1016        53.8402             0       -0.1705
49        Ni  6.7835  3.9196  1.8756  10.1705    1.1016        53.8402             0       -0.1705
50        Ni -0.6197  8.1939  1.8756  10.1705    1.1016        53.8402             0       -0.1705
51        Ni  4.3157  8.1939  1.8756  10.1705    1.1016        53.8402             0       -0.1705
52        Ni -0.6197  2.4949  3.9292  10.1366    1.0786        10.9411             0       -0.1366
53        Ni  4.3157  2.4949  3.9292  10.1366    1.0786        10.9411             0       -0.1366
54        Ni -3.0874  6.7691  3.9292  10.1366    1.0786        10.9411             0       -0.1366
55        Ni  1.8480  6.7691  3.9292  10.1366    1.0786        10.9411             0       -0.1366
56        Ni  1.8480  3.9196  5.9146  10.1417    1.0936        10.9605             0       -0.1417
57        Ni  6.7835  3.9196  5.9146  10.1417    1.0936        10.9605             0       -0.1417
58        Ni -0.6197  8.1939  5.9146  10.1417    1.0936        10.9605             0       -0.1417
59        Ni  4.3157  8.1939  5.9146  10.1417    1.0936        10.9605             0       -0.1417
60        Ni -0.6197  2.4949  7.9682  10.1730    1.0886        53.7674             1       -0.1730
61        Ni  4.3157  2.4949  7.9682  10.1730    1.0886        53.7674             1       -0.1730
62        Ni -3.0874  6.7691  7.9682  10.1730    1.0886        53.7674             1       -0.1730
63        Ni  1.8480  6.7691  7.9682  10.1730    1.0886        53.7674             1       -0.1730

In [15]:
#Done
#This was too manual but if with same function in the next block you faced a problem go back to this one again
import numpy as np
def read_CONTCAR_old(contcar_path, 
                 output_type = 'list',  # 'list' or df
                 coord_start_line_num = 9,
                 cell_dm_ang_line_num = 1,
                 cell_pars_line_num = 2, 
                 atom_types_line_num = 5, 
                 type_num_line_num = 6,
                 fractional=False):
    
    def vasp_to_coordinate(coord_line, cell_matrix, atom_type, fractional =False):
        coord_list = coord_line.split()[0:3]
        #atom_type = coord_line.split()[0]
        for n in range(len(coord_list)):
            #coord_list[n] = re.sub("d","0",coord_list[n])
            coord_list[n] = float(coord_list[n])
        coord_array = np.array(coord_list).reshape(1,3)
        if fractional == False:
            coord_array_ang = np.dot(coord_array,cell_matrix)
            return (atom_type,coord_array_ang) 
        else:
            return (atom_type,coord_array)
    
    all_coords = []
    #Extracting information from final CONTCAR
    contcar = open(contcar_path,'r')
    contcar_lines = contcar.readlines()
    contcar.close()

    ##cell matrix
    cell_dm_ang = float(contcar_lines[cell_dm_ang_line_num].split()[0])
    list_cell_matrix = [float(i) for i in contcar_lines[cell_pars_line_num].split() 
                        + contcar_lines[cell_pars_line_num + 1].split() 
                        + contcar_lines[cell_pars_line_num + 2].split()]
    cell_matrix = np.array(list_cell_matrix).reshape(3,3) * cell_dm_ang 

    ##generations of atom types list
    atom_types = contcar_lines[atom_types_line_num].split()
    type_num = [int(i) for i in contcar_lines[type_num_line_num].split()]
    atoms_list = ''
    for i in range(0,len(atom_types)):
        atoms_list = atoms_list + type_num[i] * (atom_types[i] + ' ')
    atoms_list = atoms_list.split()

    ##Reading cooordinates oof CONTCAR
    #The line number in the contcar where the first coordinates is written (start counting from zero not one)
    coordinates = contcar_lines[coord_start_line_num : coord_start_line_num + sum(type_num)]
    for num in range(len(coordinates)):    
        coordinate = vasp_to_coordinate(coordinates[num],cell_matrix, atoms_list[num],fractional=fractional)
        all_coords.append(coordinate)
        
    df = pd.DataFrame()
    atom_type = [i[0] for i in all_coords]
    x = [i[1][0][0] for i in all_coords]
    y = [i[1][0][1] for i in all_coords]
    z = [i[1][0][2] for i in all_coords]
    df['atom_type'] = atom_type
    df['x'] = x
    df['y'] = y
    df['z'] = z
    
    if output_type == 'list':
        return all_coords
    else:
        return df

In [16]:
import numpy as np
import pandas as pd
from pymatgen.core import Structure

def read_CONTCAR(file_path, fractional=False, output_type='df'):
    """
    Reads a CONTCAR file and returns atomic coordinates as a list or pandas DataFrame.

    Parameters:
        file_path (str): Path to the CONTCAR file.
        fractional (bool): If True, return fractional coordinates. If False, return real coordinates.
        output_type (str): 'list' for a list of coordinates (as 3×1 NumPy arrays), 'df' for a pandas DataFrame.

    Returns:
        list or pd.DataFrame: Atomic coordinates in requested format.
    """
    # Load structure using pymatgen
    structure = Structure.from_file(file_path)
    
    # Get atomic symbols
    atom_types = [site.species_string for site in structure]
    
    # Get coordinates (fractional or real)
    coordinates = structure.frac_coords if fractional else structure.cart_coords

    # If output_type is 'list', return a list with coordinates as (atom_type, 3×1 NumPy array)
    if output_type == 'list':
        return [(atom, np.array([[x], [y], [z]])) for atom, (x, y, z) in zip(atom_types, coordinates)]
    
    # If output_type is 'df', return a pandas DataFrame
    elif output_type == 'df':
        df = pd.DataFrame(coordinates, columns=['x', 'y', 'z'])
        df.insert(0, 'atom_type', atom_types)
        return df
    
    else:
        raise ValueError("Invalid output_type. Choose 'list' or 'df'.")

In [17]:
#test
read_CONTCAR_old('./test_repeat_structure/1_QS/1_acf_qs_to_vasp/POSCAR', 
                 output_type = 'list',  # 'list' or df
                 coord_start_line_num = 9,
                 cell_dm_ang_line_num = 1,
                 cell_pars_line_num = 2, 
                 atom_types_line_num = 5, 
                 type_num_line_num = 6,
            fractional=False)

[('Cu', array([[1.02176869e+01, 9.25331456e-03, 2.17263780e+00]])),
 ('Cu', array([[-2.66864564e-03,  8.85422663e+00,  2.12101451e+00]])),
 ('Cu', array([[6.38641664, 3.69147924, 6.24581125]])),
 ('Au', array([[2.56133234e+00, 4.24147146e-03, 8.30731071e+00]])),
 ('Ni', array([[7.66956997, 2.96948162, 4.21646253]])),
 ('Ni', array([[-1.29185966,  5.13710376,  4.24359336]]))]

In [18]:
import numpy as np
import pandas as pd
from pymatgen.core import Structure

def read_CONTCAR(file_path, fractional=False, output_type='df'):
    """
    Reads a CONTCAR file and returns atomic coordinates as a list or pandas DataFrame.

    Parameters:
        file_path (str): Path to the CONTCAR file.
        fractional (bool): If True, return fractional coordinates. If False, return real coordinates.
        output_type (str): 'list' for a list of coordinates (as 3×1 NumPy arrays), 'df' for a pandas DataFrame.

    Returns:
        list or pd.DataFrame: Atomic coordinates in requested format.
    """
    # Load structure using pymatgen
    structure = Structure.from_file(file_path)
    
    # Get atomic symbols
    atom_types = [site.species_string for site in structure]
    
    # Get coordinates (fractional or real)
    coordinates = structure.frac_coords if fractional else structure.cart_coords

    # If output_type is 'list', return a list with coordinates as (atom_type, 3×1 NumPy array)
    if output_type == 'list':
        return [(atom, np.array([[x], [y], [z]])) for atom, (x, y, z) in zip(atom_types, coordinates)]
    
    # If output_type is 'df', return a pandas DataFrame
    elif output_type == 'df':
        df = pd.DataFrame(coordinates, columns=['x', 'y', 'z'])
        df.insert(0, 'atom_type', atom_types)
        return df
    
    else:
        raise ValueError("Invalid output_type. Choose 'list' or 'df'.")

In [19]:
#test
read_CONTCAR('./test_repeat_structure/1_QS/1_acf_qs_to_vasp/POSCAR', 
                 output_type = 'df',  # 'list' or df
            fractional=True)

  atom_type         x         y         z
0        Cu  0.999837  0.001045  0.093053
1        Cu  0.499704  0.999930  0.090842
2        Cu  0.833051  0.416888  0.267505
3        Au  0.250744  0.000479  0.355798
4        Ni  0.917778  0.335351  0.180589
5        Ni  0.163726  0.580146  0.181751

In [20]:
def expand_struct_vasp(input_path, output_path, supercell_size):
    from pymatgen.core.structure import Structure
    structure = Structure.from_file(input_path)
    structure.make_supercell(supercell_size)
    structure.to(fmt = 'POSCAR',filename = output_path)
    print('Structure is Expanded')

In [21]:
expand_struct_vasp('./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.surf',
                  './test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.surf221',
                  [2,2,1])

Structure is Expanded

In [22]:
#Done
def expand_charge_file_VASP(acf_dat,
                            input_path,
                            potcar_path,
                            input_type = 'vasp',
                            supercell_size = [2,2,1]):
    """
    Expands a VASP structure by creating a supercell, extracts valence electrons from a POTCAR file, 
    and processes charge information from an acf.dat file.

    Args:
        acf_dat (str): Path to the acf.dat file containing charge information, unexpanded.
        input_path (str): Path to the input POSCAR file (VASP structure file), unexpanded.
        potcar_path (str): Path to the POTCAR file, used to extract valence electron information.
        input_type (str, optional): Specifies the type of input format. Default is 'vasp'.
        supercell_size (list, optional): Defines the expansion size for creating a supercell. Default is [2,2,1].

    Returns:
        pd.DataFrame: Expanded Bader charge data including Cartesian coordinates.
        expanded acf file: acf_dat + '.' + f'{supercell_size_str}'
    """
    #Functions that are used
    def find_element(list_, line):
        final_result = False
        for element in list_:
            if element in line:
                result = True
            else:
                result = False
            final_result = final_result or result
        return final_result
    
    from pymatgen.io.vasp.inputs import Potcar

    def get_valence_electrons_from_potcar_pymatgen(potcar_file):
        """
        Reads a POTCAR file using pymatgen and extracts the number of valence electrons for each element.

        Args:
            potcar_file (str): Path to the POTCAR file.

        Returns:
            dict: A dictionary where keys are element names and values are the number of valence electrons.
        """
        try:
            # Use pymatgen's Potcar class to parse the POTCAR file
            potcar = Potcar.from_file(potcar_file)

            # Extract element names and their ZVAL values
            valence_electrons = {entry.element: entry.nelectrons for entry in potcar}

            return valence_electrons
        except FileNotFoundError:
            raise FileNotFoundError(f"The file {potcar_file} does not exist.")
        except Exception as e:
            raise RuntimeError(f"An error occurred while parsing the POTCAR file: {e}")

    valence_electrons = get_valence_electrons_from_potcar_pymatgen(potcar_path)
    #print(valence_electrons)
    
    #start
    if len(supercell_size)!= 3:
        return 'supercell size should have this format: [int, int, int]'
    repetition = np.prod(supercell_size) #returns the product of elements
    supercell_size_str = ''.join([str(i) for i in supercell_size]) #to name the file '221'
    new_poscar_path = input_path +  '.' + f'{supercell_size_str}_dummy'
    new_acf_path = acf_dat + '.' + f'{supercell_size_str}'
    new_acf_path_dummy = acf_dat + '.' + f'dummy_{supercell_size_str}'
    new_acf = open(new_acf_path,'w')
    new_acf_dummy = open(new_acf_path_dummy,'w')



    input_ = open(input_path,'r')
    input_lines = input_.readlines()
    input_.close()
    
    #Make a supercell with the new size
    structure = Structure.from_file(input_path)
    structure.make_supercell(supercell_size)
    structure.to(fmt = 'POSCAR',filename = new_poscar_path)
    #Read the expanded poscar
    new_poscar_coordinates = read_CONTCAR(new_poscar_path,fractional=False)

    #Read nonexpanded acf.dat
    acf_dat = open(acf_dat,'r')
    acf_dat_lines = acf_dat.readlines()
    acf_dat.close()
    initial_lines = acf_dat_lines[0:2] #['    #         X           Y           Z        CHARGE     MIN DIST    ATOMIC VOL\n', ' ----------------------------  \n']
    final_lines = acf_dat_lines[-4:] #[' --------------------------------------------------------------------------------\n', '    VACUUM CHARGE: \n', 'VACUUM VOLUME:\n', 'NUMBER OF ELECTRONS:\n']


    #Write the lines of the expanded acf.dat.221
    non_rep_list = ['---','X','VACUUM','NUMBER']
    for line in acf_dat_lines:
        if find_element(non_rep_list, line):
            new_acf_dummy.write(line)
        else:
            for i in range(0, repetition):
                new_acf_dummy.write(line)

    new_acf_dummy.close()

    new_bader_df = bader_df(acf_dat=new_acf_path_dummy,
                            input_type = 'vasp',
                            input_path = new_poscar_path,
                            valence_dict = valence_electrons,
                            slab = True,
                            atom_types_line_num = 5, 
                            type_num_line_num = 6,
                            z_threshhold = 1.0)
    #os.rmtree(new_acf_dummy)

    new_poscar_df = read_CONTCAR(new_poscar_path,output_type='df')

    new_bader_df['x'] = new_poscar_df['x']
    new_bader_df['y'] = new_poscar_df['y']
    new_bader_df['z'] = new_poscar_df['z']
    
    #Writing the final acf file
    col_list = list(new_bader_df.columns)
    #print(col_list)
    all_new_acf_lines = []
    atom_number = [i + 1 for i in list(new_bader_df.index)]
    for row_id, row in new_bader_df.iterrows():
        each_atom_list = ['',
                          str(row_id + 1), 
                          str(round(row[col_list[1]],4)), 
                          str(round(row[col_list[2]],4)), 
                          str(round(row[col_list[3]],4)), 
                          str(round(row[col_list[4]],4)), 
                          str(round(row[col_list[5]],4)),  
                          str(round(row[col_list[6]],4))]
        each_line = '      '.join(each_atom_list)
        all_new_acf_lines.append(each_line) 
        
        
    for line in initial_lines:
        new_acf.write(line)  
    for line in all_new_acf_lines:
        new_acf.write(line + '\n')
    for line in final_lines:
        new_acf.write(line)
        
    new_acf.close()
        
    return new_bader_df

In [23]:
# Path to your POTCAR file
my_dir = './test_repeat_structure/0_VASP/SDA_test/3_test/'
potcar_file = my_dir + "POTCAR.surf" 
poscar_file = my_dir + 'POSCAR.surf'
acf_file = my_dir + 'ACF_surf.dat'

expand_charge_file_VASP(acf_file,
                       poscar_file,
                       potcar_file,
                       supercell_size = [2,2,1])

    atom_type             x          y         z   Charge  Min_dist  atomic_volume  surface_atom  bader_charge
0          Cu  2.761198e+00   1.992738  3.393203  10.5224    1.0820        10.5707             0        0.4776
1          Cu -2.761220e+00  11.557848  3.393203  10.5224    1.0820        10.5707             0        0.4776
2          Cu  1.380604e+01   1.992738  3.393203  10.5224    1.0820        10.5707             0        0.4776
3          Cu  8.283617e+00  11.557848  3.393203  10.5224    1.0820        10.5707             0        0.4776
4          Cu  8.283617e+00   1.992738  3.393203  10.5224    1.0820        10.5707             0        0.4776
5          Cu  2.761199e+00  11.557848  3.393203  10.5224    1.0820        10.5707             0        0.4776
6          Cu  1.932845e+01   1.992738  3.393203  10.5224    1.0820        10.5707             0        0.4776
7          Cu  1.380604e+01  11.557848  3.393203  10.5224    1.0820        10.5707             0        0.4776
8          Cu -1.086775e-05   6.775293  3.393203  10.5224    1.0820        10.5707             0        0.4776
9          Cu -5.522429e+00  16.340403  3.393203  10.5224    1.0820        10.5707             0        0.4776
10         Cu  1.104483e+01   6.775293  3.393203  10.5224    1.0820        10.5707             0        0.4776
11         Cu  5.522408e+00  16.340403  3.393203  10.5224    1.0820        10.5707             0        0.4776
12         Cu  5.522408e+00   6.775293  3.393203  10.5224    1.0820        10.5707             0        0.4776
13         Cu -1.061775e-05  16.340403  3.393203  10.5224    1.0820        10.5707             0        0.4776
14         Cu  1.656725e+01   6.775293  3.393203  10.5224    1.0820        10.5707             0        0.4776
15         Cu  1.104483e+01  16.340403  3.393203  10.5224    1.0820        10.5707             0        0.4776
16         Cu  1.105525e-05   0.398540  8.122725  10.5939    1.1076        47.5525             1        0.4061
17         Cu -5.522407e+00   9.963650  8.122725  10.5939    1.1076        47.5525             1        0.4061
18         Cu  1.104485e+01   0.398540  8.122725  10.5939    1.1076        47.5525             1        0.4061
19         Cu  5.522430e+00   9.963650  8.122725  10.5939    1.1076        47.5525             1        0.4061
20         Cu  5.522430e+00   0.398540  8.122725  10.5939    1.1076        47.5525             1        0.4061
21         Cu  1.130525e-05   9.963650  8.122725  10.5939    1.1076        47.5525             1        0.4061
22         Cu  1.656727e+01   0.398540  8.122725  10.5939    1.1076        47.5525             1        0.4061
23         Cu  1.104485e+01   9.963650  8.122725  10.5939    1.1076        47.5525             1        0.4061
24         Cu -2.761198e+00   5.181095  8.122725  10.5939    1.1076        47.5525             1        0.4061
25         Cu -8.283617e+00  14.746205  8.122725  10.5939    1.1076        47.5525             1        0.4061
26         Cu  8.283639e+00   5.181095  8.122725  10.5939    1.1076        47.5525             1        0.4061
27         Cu  2.761221e+00  14.746205  8.122725  10.5939    1.1076        47.5525             1        0.4061
28         Cu  2.761221e+00   5.181095  8.122725  10.5939    1.1076        47.5525             1        0.4061
29         Cu -2.761198e+00  14.746205  8.122725  10.5939    1.1076        47.5525             1        0.4061
30         Cu  1.380606e+01   5.181095  8.122725  10.5939    1.1076        47.5525             1        0.4061
31         Cu  8.283640e+00  14.746205  8.122725  10.5939    1.1076        47.5525             1        0.4061
32         Pt  1.105525e-05   0.398540  1.085183  10.0510    1.2429        62.6581             0       -0.0510
33         Pt -5.522407e+00   9.963650  1.085183  10.0510    1.2429        62.6581             0       -0.0510
34         Pt  1.104485e+01   0.398540  1.085183  10.0510    1.2429        62.6581             0       -0.0510
35         Pt  5.522430e+00   9.963650  1.085183  10.0510    1.2429        62.6581             0       -0.0510
36         Pt  2.761220e+00   0.404700  1.111449  10.0813    1.2520        56.8099             0       -0.0813
37         Pt -2.761198e+00   9.969810  1.111449  10.0813    1.2520        56.8099             0       -0.0813
38         Pt  1.380606e+01   0.404700  1.111449  10.0813    1.2520        56.8099             0       -0.0813
39         Pt  8.283639e+00   9.969810  1.111449  10.0813    1.2520        56.8099             0       -0.0813
40         Pt  5.522430e+00   0.398540  1.085183  10.0510    1.2429        62.6581             0       -0.0510
41         Pt  1.130525e-05   9.963650  1.085183  10.0510    1.2429        62.6581             0       -0.0510
42         Pt  1.656727e+01   0.398540  1.085183  10.0510    1.2429        62.6581             0       -0.0510
43         Pt  1.104485e+01   9.963650  1.085183  10.0510    1.2429        62.6581             0       -0.0510
44         Pt  8.283639e+00   0.404700  1.111449  10.0813    1.2520        56.8099             0       -0.0813
45         Pt  2.761221e+00   9.969810  1.111449  10.0813    1.2520        56.8099             0       -0.0813
46         Pt  1.932848e+01   0.404700  1.111449  10.0813    1.2520        56.8099             0       -0.0813
47         Pt  1.380606e+01   9.969810  1.111449  10.0813    1.2520        56.8099             0       -0.0813
48         Pt -1.385928e+00   2.786737  1.111449  10.0768    1.2378        58.9037             0       -0.0768
49         Pt -6.908347e+00  12.351847  1.111449  10.0768    1.2378        58.9037             0       -0.0768
50         Pt  9.658909e+00   2.786737  1.111449  10.0768    1.2378        58.9037             0       -0.0768
51         Pt  4.136491e+00  12.351847  1.111449  10.0768    1.2378        58.9037             0       -0.0768
52         Pt  1.385950e+00   2.786737  1.111449  10.0834    1.2378        59.4324             0       -0.0834
53         Pt -4.136468e+00  12.351847  1.111449  10.0834    1.2378        59.4324             0       -0.0834
54         Pt  1.243079e+01   2.786737  1.111449  10.0834    1.2378        59.4324             0       -0.0834
55         Pt  6.908369e+00  12.351847  1.111449  10.0834    1.2378        59.4324             0       -0.0834
56         Pt  4.136491e+00   2.786737  1.111449  10.0768    1.2378        58.9037             0       -0.0768
57         Pt -1.385928e+00  12.351847  1.111449  10.0768    1.2378        58.9037             0       -0.0768
58         Pt  1.518133e+01   2.786737  1.111449  10.0768    1.2378        58.9037             0       -0.0768
59         Pt  9.658910e+00  12.351847  1.111449  10.0768    1.2378        58.9037             0       -0.0768
60         Pt  6.908369e+00   2.786737  1.111449  10.0834    1.2378        59.4324             0       -0.0834
61         Pt  1.385951e+00  12.351847  1.111449  10.0834    1.2378        59.4324             0       -0.0834
62         Pt  1.795321e+01   2.786737  1.111449  10.0834    1.2378        59.4324             0       -0.0834
63         Pt  1.243079e+01  12.351847  1.111449  10.0834    1.2378        59.4324             0       -0.0834
64         Pt -2.761198e+00   5.181095  1.085183  10.0510    1.2429        62.6581             0       -0.0510
65         Pt -8.283617e+00  14.746205  1.085183  10.0510    1.2429        62.6581             0       -0.0510
66         Pt  8.283639e+00   5.181095  1.085183  10.0510    1.2429        62.6581             0       -0.0510
67         Pt  2.761221e+00  14.746205  1.085183  10.0510    1.2429        62.6581             0       -0.0510
68         Pt  1.118042e-05   5.187255  1.111449  10.0813    1.2520        56.8099             0       -0.0813
69         Pt -5.522407e+00  14.752365  1.111449  10.0813    1.2520        56.8099             0       -0.0813
70         Pt  1.104485e+01   5.187255  1.111449  10.0813    1.2520        56.8099             0       -0.0813
71         Pt  5.522430e+00  14.752365  1.111449  10.0813    1.2520        56.8099             0       -0.0813
72         Pt  2.761221e+00   5.181095  1.085183  10.0510    1.2429        62.6581             0       -0.0510
73         Pt -2.761198e+00  14.746205  1.085183  10.0510    1.2429        62.6581             0       -0.0510
74         Pt  1.380606e+01   5.181095  1.085183  10.0510    1.2429        62.6581             0       -0.0510
75         Pt  8.283640e+00  14.746205  1.085183  10.0510    1.2429        62.6581             0       -0.0510
76         Pt  5.522430e+00   5.187255  1.111449  10.0813    1.2520        56.8099             0       -0.0813
77         Pt  1.143042e-05  14.752365  1.111449  10.0813    1.2520        56.8099             0       -0.0813
78         Pt  1.656727e+01   5.187255  1.111449  10.0813    1.2520        56.8099             0       -0.0813
79         Pt  1.104485e+01  14.752365  1.111449  10.0813    1.2520        56.8099             0       -0.0813
80         Pt -4.147137e+00   7.569292  1.111449  10.0768    1.2378        58.9037             0       -0.0768
81         Pt -9.669556e+00  17.134402  1.111449  10.0768    1.2378        58.9037             0       -0.0768
82         Pt  6.897700e+00   7.569292  1.111449  10.0768    1.2378        58.9037             0       -0.0768
83         Pt  1.375282e+00  17.134402  1.111449  10.0768    1.2378        58.9037             0       -0.0768
84         Pt -1.375259e+00   7.569292  1.111449  10.0834    1.2378        59.4324             0       -0.0834
85         Pt -6.897677e+00  17.134402  1.111449  10.0834    1.2378        59.4324             0       -0.0834
86         Pt  9.669579e+00   7.569292  1.111449  10.0834    1.2378        59.4324             0       -0.0834
87         Pt  4.147160e+00  17.134402  1.111449  10.0834    1.2378        59.4324             0       -0.0834
88         Pt  1.375281e+00   7.569292  1.111449  10.0768    1.2378        58.9037             0       -0.0768
89         Pt -4.147137e+00  17.134402  1.111449  10.0768    1.2378        58.9037             0       -0.0768
90         Pt  1.242012e+01   7.569292  1.111449  10.0768    1.2378        58.9037             0       -0.0768
91         Pt  6.897700e+00  17.134402  1.111449  10.0768    1.2378        58.9037             0       -0.0768
92         Pt  4.147160e+00   7.569292  1.111449  10.0834    1.2378        59.4324             0       -0.0834
93         Pt -1.375259e+00  17.134402  1.111449  10.0834    1.2378        59.4324             0       -0.0834
94         Pt  1.519200e+01   7.569292  1.111449  10.0834    1.2378        59.4324             0       -0.0834
95         Pt  9.669579e+00  17.134402  1.111449  10.0834    1.2378        59.4324             0       -0.0834
96         Pt  5.206500e-08   1.992030  3.475152  10.0383    1.2417        16.2178             0       -0.0383
97         Pt -5.522418e+00  11.557140  3.475152  10.0383    1.2417        16.2178             0       -0.0383
98         Pt  1.104484e+01   1.992030  3.475152  10.0383    1.2417        16.2178             0       -0.0383
99         Pt  5.522419e+00  11.557140  3.475152  10.0383    1.2417        16.2178             0       -0.0383
100        Pt  5.522419e+00   1.992030  3.475152  10.0383    1.2417        16.2178             0       -0.0383
101        Pt  3.020650e-07  11.557140  3.475152  10.0383    1.2417        16.2178             0       -0.0383
102        Pt  1.656726e+01   1.992030  3.475152  10.0383    1.2417        16.2178             0       -0.0383
103        Pt  1.104484e+01  11.557140  3.475152  10.0383    1.2417        16.2178             0       -0.0383
104        Pt -1.381212e+00   4.384359  3.475152  10.0391    1.2452        16.2122             0       -0.0391
105        Pt -6.903631e+00  13.949469  3.475152  10.0391    1.2452        16.2122             0       -0.0391
106        Pt  9.663625e+00   4.384359  3.475152  10.0391    1.2452        16.2122             0       -0.0391
107        Pt  4.141207e+00  13.949469  3.475152  10.0391    1.2452        16.2122             0       -0.0391
108        Pt  1.381212e+00   4.384359  3.475152  10.0340    1.2417        16.2017             0       -0.0340
109        Pt -4.141206e+00  13.949469  3.475152  10.0340    1.2417        16.2017             0       -0.0340
110        Pt  1.242605e+01   4.384359  3.475152  10.0340    1.2417        16.2017             0       -0.0340
111        Pt  6.903631e+00  13.949469  3.475152  10.0340    1.2417        16.2017             0       -0.0340
112        Pt  4.141207e+00   4.384359  3.475152  10.0391    1.2452        16.2122             0       -0.0391
113        Pt -1.381212e+00  13.949469  3.475152  10.0391    1.2452        16.2122             0       -0.0391
114        Pt  1.518604e+01   4.384359  3.475152  10.0391    1.2452        16.2122             0       -0.0391
115        Pt  9.663626e+00  13.949469  3.475152  10.0391    1.2452        16.2122             0       -0.0391
116        Pt  6.903631e+00   4.384359  3.475152  10.0340    1.2417        16.2017             0       -0.0340
117        Pt  1.381213e+00  13.949469  3.475152  10.0340    1.2417        16.2017             0       -0.0340
118        Pt  1.794847e+01   4.384359  3.475152  10.0340    1.2417        16.2017             0       -0.0340
119        Pt  1.242605e+01  13.949469  3.475152  10.0340    1.2417        16.2017             0       -0.0340
120        Pt -2.761209e+00   6.774585  3.475152  10.0383    1.2417        16.2178             0       -0.0383
121        Pt -8.283628e+00  16.339695  3.475152  10.0383    1.2417        16.2178             0       -0.0383
122        Pt  8.283628e+00   6.774585  3.475152  10.0383    1.2417        16.2178             0       -0.0383
123        Pt  2.761210e+00  16.339695  3.475152  10.0383    1.2417        16.2178             0       -0.0383
124        Pt  2.761210e+00   6.774585  3.475152  10.0383    1.2417        16.2178             0       -0.0383
125        Pt -2.761209e+00  16.339695  3.475152  10.0383    1.2417        16.2178             0       -0.0383
126        Pt  1.380605e+01   6.774585  3.475152  10.0383    1.2417        16.2178             0       -0.0383
127        Pt  8.283629e+00  16.339695  3.475152  10.0383    1.2417        16.2178             0       -0.0383
128        Pt -4.142421e+00   9.166914  3.475152  10.0391    1.2452        16.2122             0       -0.0391
129        Pt -9.664840e+00  18.732024  3.475152  10.0391    1.2452        16.2122             0       -0.0391
130        Pt  6.902416e+00   9.166914  3.475152  10.0391    1.2452        16.2122             0       -0.0391
131        Pt  1.379998e+00  18.732024  3.475152  10.0391    1.2452        16.2122             0       -0.0391
132        Pt -1.379997e+00   9.166914  3.475152  10.0340    1.2417        16.2017             0       -0.0340
133        Pt -6.902415e+00  18.732024  3.475152  10.0340    1.2417        16.2017             0       -0.0340
134        Pt  9.664841e+00   9.166914  3.475152  10.0340    1.2417        16.2017             0       -0.0340
135        Pt  4.142422e+00  18.732024  3.475152  10.0340    1.2417        16.2017             0       -0.0340
136        Pt  1.379997e+00   9.166914  3.475152  10.0391    1.2452        16.2122             0       -0.0391
137        Pt -4.142421e+00  18.732024  3.475152  10.0391    1.2452        16.2122             0       -0.0391
138        Pt  1.242483e+01   9.166914  3.475152  10.0391    1.2452        16.2122             0       -0.0391
139        Pt  6.902416e+00  18.732024  3.475152  10.0391    1.2452        16.2122             0       -0.0391
140        Pt  4.142422e+00   9.166914  3.475152  10.0340    1.2417        16.2017             0       -0.0340
141        Pt -1.379997e+00  18.732024  3.475152  10.0340    1.2417        16.2017             0       -0.0340
142        Pt  1.518726e+01   9.166914  3.475152  10.0340    1.2417        16.2017             0       -0.0340
143        Pt  9.664841e+00  18.732024  3.475152  10.0340    1.2417        16.2017             0       -0.0340
144        Pt  1.382527e+00   1.196748  5.783080  10.0192    1.2411        16.0864             0       -0.0192
145        Pt -4.139892e+00  10.761858  5.783080  10.0192    1.2411        16.0864             0       -0.0192
146        Pt  1.242736e+01   1.196748  5.783080  10.0192    1.2411        16.0864             0       -0.0192
147        Pt  6.904946e+00  10.761858  5.783080  10.0192    1.2411        16.0864             0       -0.0192
148        Pt  4.139892e+00   1.196748  5.783080  10.0238    1.2411        16.1032             0       -0.0238
149        Pt -1.382526e+00  10.761858  5.783080  10.0238    1.2411        16.1032             0       -0.0238
150        Pt  1.518473e+01   1.196748  5.783080  10.0238    1.2411        16.1032             0       -0.0238
151        Pt  9.662311e+00  10.761858  5.783080  10.0238    1.2411        16.1032             0       -0.0238
152        Pt  6.904945e+00   1.196748  5.783080  10.0192    1.2411        16.0864             0       -0.0192
153        Pt  1.382527e+00  10.761858  5.783080  10.0192    1.2411        16.0864             0       -0.0192
154        Pt  1.794978e+01   1.196748  5.783080  10.0192    1.2411        16.0864             0       -0.0192
155        Pt  1.242736e+01  10.761858  5.783080  10.0192    1.2411        16.0864             0       -0.0192
156        Pt  9.662311e+00   1.196748  5.783080  10.0238    1.2411        16.1032             0       -0.0238
157        Pt  4.139893e+00  10.761858  5.783080  10.0238    1.2411        16.1032             0       -0.0238
158        Pt  2.070715e+01   1.196748  5.783080  10.0238    1.2411        16.1032             0       -0.0238
159        Pt  1.518473e+01  10.761858  5.783080  10.0238    1.2411        16.1032             0       -0.0238
160        Pt  9.375000e-08   3.586916  5.789681   9.9566    1.2432        15.3488             0        0.0434
161        Pt -5.522418e+00  13.152026  5.789681   9.9566    1.2432        15.3488             0        0.0434
162        Pt  1.104484e+01   3.586916  5.789681   9.9566    1.2432        15.3488             0        0.0434
163        Pt  5.522419e+00  13.152026  5.789681   9.9566    1.2432        15.3488             0        0.0434
164        Pt  2.761209e+00   3.584697  5.783080  10.0122    1.2416        16.0547             0       -0.0122
165        Pt -2.761209e+00  13.149807  5.783080  10.0122    1.2416        16.0547             0       -0.0122
166        Pt  1.380605e+01   3.584697  5.783080  10.0122    1.2416        16.0547             0       -0.0122
167        Pt  8.283628e+00  13.149807  5.783080  10.0122    1.2416        16.0547             0       -0.0122
168        Pt  5.522419e+00   3.586916  5.789681   9.9566    1.2432        15.3488             0        0.0434
169        Pt  3.437500e-07  13.152026  5.789681   9.9566    1.2432        15.3488             0        0.0434
170        Pt  1.656726e+01   3.586916  5.789681   9.9566    1.2432        15.3488             0        0.0434
171        Pt  1.104484e+01  13.152026  5.789681   9.9566    1.2432        15.3488             0        0.0434
172        Pt  8.283628e+00   3.584697  5.783080  10.0122    1.2416        16.0547             0       -0.0122
173        Pt  2.761210e+00  13.149807  5.783080  10.0122    1.2416        16.0547             0       -0.0122
174        Pt  1.932847e+01   3.584697  5.783080  10.0122    1.2416        16.0547             0       -0.0122
175        Pt  1.380605e+01  13.149807  5.783080  10.0122    1.2416        16.0547             0       -0.0122
176        Pt -1.378683e+00   5.979303  5.783080  10.0192    1.2411        16.0864             0       -0.0192
177        Pt -6.901101e+00  15.544413  5.783080  10.0192    1.2411        16.0864             0       -0.0192
178        Pt  9.666155e+00   5.979303  5.783080  10.0192    1.2411        16.0864             0       -0.0192

In [24]:
bader_df(acf_file, poscar_file, 
         valence_dict = get_valence_electrons_from_potcar_pymatgen(potcar_file),
         input_type ='vasp')

   atom_type       x       y       z   Charge  Min_dist  atomic_volume  surface_atom  bader_charge
0         Cu  2.7612  1.9927  3.3932  10.5224    1.0820        10.5707             0        0.4776
1         Cu  8.2836  1.9927  3.3932  10.5224    1.0820        10.5707             0        0.4776
2         Cu  0.0000  6.7753  3.3932  10.5224    1.0820        10.5707             0        0.4776
3         Cu  5.5224  6.7753  3.3932  10.5224    1.0820        10.5707             0        0.4776
4         Cu  0.0000  0.3985  8.1227  10.5939    1.1076        47.5525             1        0.4061
5         Cu  5.5224  0.3985  8.1227  10.5939    1.1076        47.5525             1        0.4061
6         Cu -2.7612  5.1811  8.1227  10.5939    1.1076        47.5525             1        0.4061
7         Cu  2.7612  5.1811  8.1227  10.5939    1.1076        47.5525             1        0.4061
8         Pt  0.0000  0.3985  1.0852  10.0510    1.2429        62.6581             0       -0.0510
9         Pt  2.7612  0.4047  1.1114  10.0813    1.2520        56.8099             0       -0.0813
10        Pt  5.5224  0.3985  1.0852  10.0510    1.2429        62.6581             0       -0.0510
11        Pt  8.2836  0.4047  1.1114  10.0813    1.2520        56.8099             0       -0.0813
12        Pt -1.3859  2.7867  1.1114  10.0768    1.2378        58.9037             0       -0.0768
13        Pt  1.3859  2.7867  1.1114  10.0834    1.2378        59.4324             0       -0.0834
14        Pt  4.1365  2.7867  1.1114  10.0768    1.2378        58.9037             0       -0.0768
15        Pt  6.9084  2.7867  1.1114  10.0834    1.2378        59.4324             0       -0.0834
16        Pt -2.7612  5.1811  1.0852  10.0510    1.2429        62.6581             0       -0.0510
17        Pt  0.0000  5.1873  1.1114  10.0813    1.2520        56.8099             0       -0.0813
18        Pt  2.7612  5.1811  1.0852  10.0510    1.2429        62.6581             0       -0.0510
19        Pt  5.5224  5.1873  1.1114  10.0813    1.2520        56.8099             0       -0.0813
20        Pt -4.1472  7.5693  1.1114  10.0768    1.2378        58.9037             0       -0.0768
21        Pt -1.3753  7.5693  1.1114  10.0834    1.2378        59.4324             0       -0.0834
22        Pt  1.3753  7.5693  1.1114  10.0768    1.2378        58.9037             0       -0.0768
23        Pt  4.1471  7.5693  1.1114  10.0834    1.2378        59.4324             0       -0.0834
24        Pt  0.0000  1.9920  3.4752  10.0383    1.2417        16.2178             0       -0.0383
25        Pt  5.5224  1.9920  3.4752  10.0383    1.2417        16.2178             0       -0.0383
26        Pt -1.3812  4.3844  3.4752  10.0391    1.2452        16.2122             0       -0.0391
27        Pt  1.3812  4.3844  3.4752  10.0340    1.2417        16.2017             0       -0.0340
28        Pt  4.1412  4.3844  3.4752  10.0391    1.2452        16.2122             0       -0.0391
29        Pt  6.9036  4.3844  3.4752  10.0340    1.2417        16.2017             0       -0.0340
30        Pt -2.7612  6.7746  3.4752  10.0383    1.2417        16.2178             0       -0.0383
31        Pt  2.7612  6.7746  3.4752  10.0383    1.2417        16.2178             0       -0.0383
32        Pt -4.1424  9.1669  3.4752  10.0391    1.2452        16.2122             0       -0.0391
33        Pt -1.3800  9.1669  3.4752  10.0340    1.2417        16.2017             0       -0.0340
34        Pt  1.3800  9.1669  3.4752  10.0391    1.2452        16.2122             0       -0.0391
35        Pt  4.1424  9.1669  3.4752  10.0340    1.2417        16.2017             0       -0.0340
36        Pt  1.3825  1.1967  5.7831  10.0192    1.2411        16.0864             0       -0.0192
37        Pt  4.1399  1.1967  5.7831  10.0238    1.2411        16.1032             0       -0.0238
38        Pt  6.9049  1.1967  5.7831  10.0192    1.2411        16.0864             0       -0.0192
39        Pt  9.6623  1.1967  5.7831  10.0238    1.2411        16.1032             0       -0.0238
40        Pt  0.0000  3.5869  5.7897   9.9566    1.2432        15.3488             0        0.0434
41        Pt  2.7612  3.5847  5.7831  10.0122    1.2416        16.0547             0       -0.0122
42        Pt  5.5224  3.5869  5.7897   9.9566    1.2432        15.3488             0        0.0434
43        Pt  8.2836  3.5847  5.7831  10.0122    1.2416        16.0547             0       -0.0122
44        Pt -1.3787  5.9793  5.7831  10.0192    1.2411        16.0864             0       -0.0192
45        Pt  1.3787  5.9793  5.7831  10.0238    1.2411        16.1032             0       -0.0238
46        Pt  4.1437  5.9793  5.7831  10.0192    1.2411        16.0864             0       -0.0192
47        Pt  6.9011  5.9793  5.7831  10.0238    1.2411        16.1032             0       -0.0238
48        Pt -2.7612  8.3695  5.7897   9.9566    1.2432        15.3488             0        0.0434
49        Pt  0.0000  8.3673  5.7831  10.0122    1.2416        16.0547             0       -0.0122
50        Pt  2.7612  8.3695  5.7897   9.9566    1.2432        15.3488             0        0.0434
51        Pt  5.5224  8.3673  5.7831  10.0122    1.2416        16.0547             0       -0.0122
52        Pt  2.7612  0.3928  8.1302  10.1546    1.2612        65.8283             1       -0.1546
53        Pt  8.2836  0.3928  8.1302  10.1546    1.2612        65.8283             1       -0.1546
54        Pt -1.3756  2.7927  8.1302  10.1572    1.2377        66.3043             1       -0.1572
55        Pt  1.3756  2.7927  8.1302  10.1563    1.2377        67.1726             1       -0.1563
56        Pt  4.1468  2.7927  8.1302  10.1572    1.2377        66.3043             1       -0.1572
57        Pt  6.8980  2.7927  8.1302  10.1563    1.2377        67.1726             1       -0.1563
58        Pt  0.0000  5.1753  8.1302  10.1546    1.2612        65.8283             1       -0.1546
59        Pt  5.5224  5.1753  8.1302  10.1546    1.2612        65.8283             1       -0.1546
60        Pt -4.1368  7.5753  8.1302  10.1572    1.2377        66.3043             1       -0.1572
61        Pt -1.3856  7.5753  8.1302  10.1563    1.2377        67.1726             1       -0.1563
62        Pt  1.3856  7.5753  8.1302  10.1572    1.2377        66.3043             1       -0.1572
63        Pt  4.1368  7.5753  8.1302  10.1563    1.2377        67.1726             1       -0.1563

In [25]:
#Done
from pymatgen.core import Structure
from pymatgen.io.vasp import Poscar
import numpy as np

def keep_central_2atmolecule(poscar_file, repetition, molecule_atoms, output_file="POSCAR_central_molecule"):
    """
    Repeats a structure and retains only the central molecule in the supercell, explicitly handling periodic boundaries. 
    However this script only works for biatomic molecules and does not work for N2H or NH3.
    
    Parameters:
        poscar_file (str): Path to the initial POSCAR file.
        repetition (tuple): Repetition factors along x, y, z (e.g., (2, 2, 1)).
        molecule_atoms (list): List of atom types that form the molecule (e.g., ["N"] for N2).
        output_file (str): Path to save the resulting POSCAR file (default: "POSCAR_central_molecule").
    
    Returns:
        list of numpy arrays: Coordinates of the central molecule in fractional format.
    """
    # Load the initial structure

    structure = Structure.from_file(poscar_file)

    # Repeat the structure
    scaling_matrix = [[repetition[0], 0, 0],
                      [0, repetition[1], 0],
                      [0, 0, repetition[2]]]
    supercell = structure * scaling_matrix

    # Identify the geometric center of the supercell
    cell_center = np.array([0.5, 0.5, 0.5])  # Center in fractional coordinates

    # Find indices of atoms belonging to the specified molecule
    molecule_indices = [i for i, site in enumerate(supercell) if site.species_string in molecule_atoms]
    print(molecule_indices)
    # Pair atoms in the molecule (assuming they are bonded), explicitly handling periodic boundaries
    molecule_pairs = []
    cutoff_distance = 1.5  # Typical bond distance, adjust if needed
    used_indices = set()

    for i in molecule_indices:
        if i in used_indices:
            continue
        for j in molecule_indices:
            if j > i and j not in used_indices:
                # Calculate fractional distance, considering periodic boundaries
                frac_diff = supercell[j].frac_coords - supercell[i].frac_coords
                frac_diff -= np.round(frac_diff)  # Adjust for PBC
                dist = np.linalg.norm(np.dot(frac_diff, supercell.lattice.matrix))
                if dist <= cutoff_distance:
                    molecule_pairs.append((i, j))
                    used_indices.update([i, j])
                    break

    # Find the molecule closest to the geometric center
    def pair_distance_to_center(pair):
        atom1_coords = supercell[pair[0]].frac_coords
        atom2_coords = supercell[pair[1]].frac_coords
        # Correct fractional coordinates for PBC
        frac_diff = atom2_coords - atom1_coords
        frac_diff -= np.round(frac_diff)  # Adjust for PBC
        atom2_coords_corrected = atom1_coords + frac_diff
        center_of_mass = (atom1_coords + atom2_coords_corrected) / 2
        # Ensure center_of_mass is within the unit cell
        center_of_mass %= 1.0
        return np.linalg.norm(center_of_mass - cell_center)

    central_pair = min(molecule_pairs, key=pair_distance_to_center)

    # Extract coordinates of the central molecule
    atom1_coords = supercell[central_pair[0]].frac_coords
    atom2_coords = supercell[central_pair[1]].frac_coords
    frac_diff = atom2_coords - atom1_coords
    frac_diff -= np.round(frac_diff)  # Adjust for PBC
    atom2_coords_corrected = atom1_coords + frac_diff
    central_molecule_coords = [atom1_coords, atom2_coords_corrected % 1.0]

    # Create a new structure retaining only the central molecule
    central_structure = supercell.copy()
    central_structure.remove_sites([index for pair in molecule_pairs if pair != central_pair for index in pair])

    # Save the resulting structure
    Poscar(central_structure).write_file(output_file)
    print(f"Central molecule saved to {output_file}")

    # Return the central molecule's fractional coordinates
    return central_molecule_coords

In [26]:
#TEST two atom mol
mol_list = ['N2',"H2",
           # 'N2H',"NH3"
           ]
def atom_types(mol_name):
    my_list = []
    for i in mol_name:
        if i == 'N' or i == 'H':
            my_list.append(i)
    return my_list
for mol in mol_list:
    input_path = f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s5{mol}'
    output_path = f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s5{mol}_expanded_centralmol'
    keep_central_2atmolecule(
        poscar_file=input_path,  # Input POSCAR file
        repetition=(2, 2, 1),  # Repetition factors
        molecule_atoms=atom_types(mol),  # Atoms forming the molecule (e.g., N2)
        output_file=output_path # Output file
    )

[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s5N2_expanded_centralmol
[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s5H2_expanded_centralmol

In [27]:
#Done
from pymatgen.core import Structure
from pymatgen.io.vasp import Poscar
import numpy as np

def keep_central_3_4atmolecule(poscar_file, repetition, molecule_atoms, output_file="POSCAR_central_molecule"):
    """
    Repeats a structure and retains only the central molecule in the supercell, explicitly handling periodic boundaries.
    Supports multi-atom molecules such as N2H or NH3 but 'not' biatomic molecule.
    
    Parameters:
        poscar_file (str): Path to the initial POSCAR file.
        repetition (tuple): Repetition factors along x, y, z (e.g., (2, 2, 1)).
        molecule_atoms (list): List of atom types that form the molecule (e.g., ["N", "H"] for NH3).
        output_file (str): Path to save the resulting POSCAR file (default: "POSCAR_central_molecule").
    
    Returns:
        list of numpy arrays: Coordinates of the central molecule in fractional format.
    """
    # Load the initial structure
    structure = Structure.from_file(poscar_file)

    # Repeat the structure
    scaling_matrix = [[repetition[0], 0, 0],
                      [0, repetition[1], 0],
                      [0, 0, repetition[2]]]
    supercell = structure * scaling_matrix

    # Identify the geometric center of the supercell
    cell_center = np.array([0.5, 0.5, 0.5])  # Center in fractional coordinates

    # Find indices of atoms belonging to the specified molecule
    molecule_indices = [i for i, site in enumerate(supercell) if site.species_string in molecule_atoms]

    # Group atoms into molecules based on a bonding cutoff distance
    cutoff_distance = 1.5  # Adjust as needed
    molecule_groups = []
    visited_indices = set()

    for i in molecule_indices:
        if i in visited_indices:
            continue
        group = [i]
        visited_indices.add(i)
        # Find all bonded atoms in the molecule
        for j in molecule_indices:
            if j not in visited_indices:
                for atom_index in group:
                    # Calculate fractional distance, considering PBC
                    frac_diff = supercell[j].frac_coords - supercell[atom_index].frac_coords
                    frac_diff -= np.round(frac_diff)  # Adjust for PBC
                    dist = np.linalg.norm(np.dot(frac_diff, supercell.lattice.matrix))
                    if dist <= cutoff_distance:
                        group.append(j)
                        visited_indices.add(j)
                        break
        molecule_groups.append(group)

    # Find the molecule closest to the geometric center
    def group_distance_to_center(group):
        # Calculate the center of mass of the group
        frac_coords = [supercell[i].frac_coords for i in group]
        frac_coords = np.array(frac_coords)
        center_of_mass = frac_coords.mean(axis=0) % 1.0
        return np.linalg.norm(center_of_mass - cell_center)

    central_group = min(molecule_groups, key=group_distance_to_center)

    # Extract coordinates of the central molecule
    central_molecule_coords = [supercell[i].frac_coords for i in central_group]

    # Create a new structure retaining only the central molecule
    central_structure = supercell.copy()
    central_structure.remove_sites([i for group in molecule_groups if group != central_group for i in group])

    # Save the resulting structure
    Poscar(central_structure).write_file(output_file)
    print(f"Central molecule saved to {output_file}")

    # Return the central molecule's fractional coordinates
    return central_molecule_coords

In [28]:
#TEST 3_4 atom molecule
mol_list = [
           # 'N2',"H2",
            'N2H',
   # "NH3"
           ]
def atom_types(mol_name):
    my_list = []
    for i in mol_name:
        if i == 'N' or i == 'H':
            my_list.append(i)
    return my_list
for mol in mol_list:
    input_path = f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s8{mol}'
    output_path = f'./test_repeat_structure/0_VASP/SDA_test/POSCAR.s8{mol}_expanded_centralmol'
    mol_coord = keep_central_3_4atmolecule(
        poscar_file=input_path,  # Input POSCAR file
        repetition=(2, 2, 1),  # Repetition factors
        molecule_atoms=atom_types(mol),  # Atoms forming the molecule (e.g., N2)
        output_file=output_path # Output file
    )

Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/POSCAR.s8N2H_expanded_centralmol

In [29]:
#Done
#mol = "N2H"
#surface_pos = f'./test_repeat_structure/0_VASP/SDA_test/POSCAR.surf221'
#dummy_pos =   f'./test_repeat_structure/0_VASP/SDA_test/POSCAR.s8{mol}_expanded_centralmol'
#out_file = f'./test_repeat_structure/0_VASP/SDA_test/POSCAR.s8{mol}_final_expanded_centralmol'
#mol_atoms = atom_types(mol)


def add_molecule_to_surface(dummy_poscar_path, 
                            main_poscar_path, 
                            output_poscar_path, 
                            molecule_species):
    """
    Adds molecule coordinates from the dummy POSCAR to the main POSCAR based on the specified species.
    
    Parameters:
    - dummy_poscar_path (str): Path to the dummy POSCAR file containing the surface + molecule.
    - main_poscar_path (str): Path to the main POSCAR file containing only the surface we want to use.
    - output_poscar_path (str): Path to save the updated POSCAR file.
    - molecule_species (list): List of species names for the molecule (e.g., ['N', 'H']).
    """
    def find_coordinate_start(poscar_lines):
        """
        Determines the starting line for coordinates in a POSCAR file.

        Parameters:
        - poscar_lines (list): List of lines from a POSCAR file.

        Returns:
        - int: The starting line number for coordinates (either 8 or 9).
        """
        
        
        # Check if line 7 contains the "Selective dynamics" keyword
        if poscar_lines[7].strip().lower() == "selective dynamics":
            return 9  # Coordinates start on line 9
        return 8  # Coordinates start on line 8
    
    
    # Read both POSCAR files
    with open(dummy_poscar_path, 'r') as f:
        dummy_poscar = f.readlines()
    with open(main_poscar_path, 'r') as f:
        main_poscar = f.readlines()
    

    # Extract species and atom counts from the dummy POSCAR
    dummy_species = dummy_poscar[5].strip().split()
    print('dummy species',dummy_species)
    dummy_atom_counts = list(map(int, dummy_poscar[6].strip().split()))
    print('dummy counts', dummy_atom_counts)
    
    # Calculate the starting line for coordinates in the dummy POSCAR
    total_surface_atoms = sum(dummy_atom_counts[:len(main_poscar[5].strip().split())])  # Surface atom count
    total_atom_counts = sum(dummy_atom_counts)
    print('dummy number of surface atoms',total_surface_atoms)
    coordinates_start = find_coordinate_start(dummy_poscar)  # Coordinates start after species and atom count lines
    coordinates = dummy_poscar[coordinates_start: coordinates_start + total_atom_counts]
    #print('dummy last coordinate',coordinates)

    # Extract molecule coordinates based on the provided species
    molecule_coordinates = []
    for species in molecule_species:
        index = dummy_species.index(species)
        count = dummy_atom_counts[index]
        count_atoms_before = 0
        for n in range(0, index):
            count_atoms_before = count_atoms_before + dummy_atom_counts[n]
        start_mol_coord = count_atoms_before
        line_num = coordinates[count_atoms_before:count_atoms_before + count]
        molecule_coordinates.extend(line_num)
    print('mol_coords',molecule_coordinates)

    # Update species and atom counts in the main POSCAR
    main_species = main_poscar[5].strip().split()
    print('main_species',main_species)
    
    main_atom_counts = list(map(int, main_poscar[6].strip().split()))
    print('main_atom_counts',main_atom_counts)

    updated_species = main_species + molecule_species
    print('updated_species',updated_species)
    updated_atom_counts = main_atom_counts + [dummy_atom_counts[dummy_species.index(species)] for species in molecule_species]
    print('updated_atom_counts',updated_atom_counts)
    # Write the updated POSCAR
    with open(output_poscar_path, 'w') as f:
        # Write the unchanged header and lattice information
        f.writelines(main_poscar[:5])
        # Write the updated species and atom counts
        f.write(" ".join(updated_species) + "\n")
        f.write(" ".join(map(str, updated_atom_counts)) + "\n")
        # Write the rest of the main POSCAR
        f.writelines(main_poscar[7:])
        # Append molecule coordinates in the order of species
        f.writelines(molecule_coordinates)

In [30]:
mol = 'N2H'
surface_pos = f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.surf221'
dummy_pos =   f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s8{mol}_expanded_centralmol'
out_file = f'./test_repeat_structure/0_VASP/SDA_test/0_test/POSCAR.s8{mol}_final_expanded_centralmol'
mol_atoms = atom_types(mol)

add_molecule_to_surface(dummy_pos, 
                        surface_pos, 
                        out_file, 
                        mol_atoms)

dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [192, 64, 2, 1]
dummy number of surface atoms 256
mol_coords ['0.583429 0.479638 0.384931 T T T N\n', '0.529737 0.489771 0.389697 T T T N\n', '0.512933 0.491065 0.437131 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [192, 64]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [192, 64, 2, 1]

In [31]:
mol_list = ['N2','H2','N2H','NH3']
test_numbers = [1, 2, 3, 4, 5, 6]
for test_number in test_numbers:
    test_dir = f'./test_repeat_structure/0_VASP/SDA_test/{test_number}_test/'
    surf_input = test_dir + 'POSCAR.surf'
    surf_acf = test_dir + 'ACF_surf.dat'

    for mol in mol_list:
        mol_atoms = atom_types(mol)
        mol_surf_dummy = test_dir + f'POSCAR.{mol}'
        expand_struct_vasp(surf_input, 
                       surf_input + '221',
                           [2,2,1])

        if len(mol_atoms) == 1:
            keep_central_2atmolecule(mol_surf_dummy,
                                    [2,2,1],
                                    mol_atoms,
                                    output_file= mol_surf_dummy + '_cent221')
        else:
            keep_central_3_4atmolecule(mol_surf_dummy,
                                    [2,2,1],
                                    mol_atoms,
                                    output_file= mol_surf_dummy + '_cent221')   

        add_molecule_to_surface(mol_surf_dummy + '_cent221',
                                surf_input + '221',
                                mol_surf_dummy + '_final',
                                mol_atoms)

Structure is Expanded
[336, 337, 338, 339, 340, 341, 342, 343]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.N2_cent221
dummy species ['Pt', 'V', 'N']
dummy counts [296, 40, 2]
dummy number of surface atoms 336
mol_coords ['0.662380 0.663912 0.407636 T T T N\n', '0.681266 0.702721 0.407636 T T T N\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N']
updated_atom_counts [296, 40, 2]
Structure is Expanded
[336, 337, 338, 339, 340, 341, 342, 343]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.H2_cent221
dummy species ['Pt', 'V', 'H']
dummy counts [296, 40, 2]
dummy number of surface atoms 336
mol_coords ['0.662379 0.671350 0.407636 T T T H\n', '0.681268 0.695282 0.407636 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'H']
updated_atom_counts [296, 40, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.N2H_cent221
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [296, 40, 2, 1]
dummy number of surface atoms 336
mol_coords ['0.671823 0.683316 0.407636 T T T N\n', '0.606075 0.689987 0.412009 T T T N\n', '0.586569 0.694653 0.455525 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [296, 40, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.NH3_cent221
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [296, 40, 1, 3]
dummy number of surface atoms 336
mol_coords ['0.671823 0.683316 0.407636 T T T N\n', '0.627012 0.698878 0.424071 T T T H\n', '0.713396 0.702565 0.424093 T T T H\n', '0.675183 0.652859 0.424073 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [296, 40, 1, 3]
Structure is Expanded
[288, 289, 290, 291, 292, 293, 294, 295]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/2_test/POSCAR.N2_cent221
dummy species ['Ni', 'Zn', 'N']
dummy counts [144, 144, 2]
dummy number of surface atoms 288
mol_coords ['0.531496 0.467041 0.350732 T T T N\n', '0.551837 0.509110 0.350732 T T T N\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N']
updated_atom_counts [144, 144, 2]
Structure is Expanded
[288, 289, 290, 291, 292, 293, 294, 295]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/2_test/POSCAR.H2_cent221
dummy species ['Ni', 'Zn', 'H']
dummy counts [144, 144, 2]
dummy number of surface atoms 288
mol_coords ['0.531496 0.475104 0.350732 T T T H\n', '0.551837 0.501046 0.350732 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'H']
updated_atom_counts [144, 144, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/2_test/POSCAR.N2H_cent221
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [144, 144, 2, 1]
dummy number of surface atoms 288
mol_coords ['0.541667 0.488075 0.350732 T T T N\n', '0.470880 0.494885 0.355715 T T T N\n', '0.449857 0.495754 0.405305 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [144, 144, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/2_test/POSCAR.NH3_cent221
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [144, 144, 1, 3]
dummy number of surface atoms 288
mol_coords ['0.541667 0.488075 0.350732 T T T N\n', '0.493416 0.503362 0.369460 T T T H\n', '0.586421 0.507356 0.369485 T T T H\n', '0.545270 0.453477 0.369463 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [144, 144, 1, 3]
Structure is Expanded
[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/3_test/POSCAR.N2_cent221
dummy species ['Cu', 'Pt', 'N']
dummy counts [32, 224, 2]
dummy number of surface atoms 256
mol_coords ['0.301460 0.618011 0.392619 T T T N\n', '0.344524 0.673957 0.392619 T T T N\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N']
updated_atom_counts [32, 224, 2]
Structure is Expanded
[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/3_test/POSCAR.H2_cent221
dummy species ['Cu', 'Pt', 'H']
dummy counts [32, 224, 2]
dummy number of surface atoms 256
mol_coords ['0.306822 0.628733 0.392619 T T T H\n', '0.339162 0.663234 0.392619 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'H']
updated_atom_counts [32, 224, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/3_test/POSCAR.N2H_cent221
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [32, 224, 2, 1]
dummy number of surface atoms 256
mol_coords ['0.322992 0.645983 0.392619 T T T N\n', '0.275007 0.655039 0.397386 T T T N\n', '0.259990 0.656196 0.444820 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [32, 224, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/3_test/POSCAR.NH3_cent221
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [32, 224, 1, 3]
dummy number of surface atoms 256
mol_coords ['0.322992 0.645983 0.392619 T T T N\n', '0.297362 0.666313 0.410533 T T T H\n', '0.369014 0.671625 0.410558 T T T H\n', '0.302659 0.599972 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [32, 224, 1, 3]
Structure is Expanded
[336, 337, 338, 339, 340, 341, 342, 343]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/4_test/POSCAR.N2_cent221
dummy species ['Pt', 'V', 'N']
dummy counts [296, 40, 2]
dummy number of surface atoms 336
mol_coords ['0.490506 0.413830 0.407766 T T T N\n', '0.509392 0.452638 0.407766 T T T N\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N']
updated_atom_counts [296, 40, 2]
Structure is Expanded
[336, 337, 338, 339, 340, 341, 342, 343]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/4_test/POSCAR.H2_cent221
dummy species ['Pt', 'V', 'H']
dummy counts [296, 40, 2]
dummy number of surface atoms 336
mol_coords ['0.490504 0.421268 0.407766 T T T H\n', '0.509393 0.445200 0.407766 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'H']
updated_atom_counts [296, 40, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/4_test/POSCAR.N2H_cent221
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [296, 40, 2, 1]
dummy number of surface atoms 336
mol_coords ['0.499949 0.433234 0.407766 T T T N\n', '0.434201 0.439904 0.412139 T T T N\n', '0.414695 0.444571 0.455655 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [296, 40, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/4_test/POSCAR.NH3_cent221
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [296, 40, 1, 3]
dummy number of surface atoms 336
mol_coords ['0.499949 0.433234 0.407766 T T T N\n', '0.455138 0.448795 0.424201 T T T H\n', '0.541523 0.452483 0.424223 T T T H\n', '0.503309 0.402776 0.424203 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [296, 40, 1, 3]
Structure is Expanded
[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/5_test/POSCAR.N2_cent221
dummy species ['Cu', 'Pt', 'N']
dummy counts [32, 224, 2]
dummy number of surface atoms 256
mol_coords ['0.655552 0.576193 0.392619 T T T N\n', '0.698615 0.632140 0.392619 T T T N\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N']
updated_atom_counts [32, 224, 2]
Structure is Expanded
[256, 257, 258, 259, 260, 261, 262, 263]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/5_test/POSCAR.H2_cent221
dummy species ['Cu', 'Pt', 'H']
dummy counts [32, 224, 2]
dummy number of surface atoms 256
mol_coords ['0.660914 0.586916 0.392619 T T T H\n', '0.693253 0.621417 0.392619 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'H']
updated_atom_counts [32, 224, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/5_test/POSCAR.N2H_cent221
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [32, 224, 2, 1]
dummy number of surface atoms 256
mol_coords ['0.677084 0.604166 0.392619 T T T N\n', '0.629099 0.613223 0.397386 T T T N\n', '0.614081 0.614379 0.444820 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [32, 224, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/5_test/POSCAR.NH3_cent221
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [32, 224, 1, 3]
dummy number of surface atoms 256
mol_coords ['0.677084 0.604166 0.392619 T T T N\n', '0.651454 0.624496 0.410533 T T T H\n', '0.723105 0.629808 0.410558 T T T H\n', '0.656751 0.558155 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [32, 224]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [32, 224, 1, 3]
Structure is Expanded

[288, 289, 290, 291, 292, 293, 294, 295]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/6_test/POSCAR.N2_cent221
dummy species ['Ni', 'Zn', 'N']
dummy counts [144, 144, 2]
dummy number of surface atoms 288
mol_coords ['0.448163 0.661475 0.356978 T T T N\n', '0.468504 0.703545 0.356978 T T T N\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N']
updated_atom_counts [144, 144, 2]
Structure is Expanded
[288, 289, 290, 291, 292, 293, 294, 295]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/6_test/POSCAR.H2_cent221
dummy species ['Ni', 'Zn', 'H']
dummy counts [144, 144, 2]
dummy number of surface atoms 288
mol_coords ['0.448163 0.669539 0.356978 T T T H\n', '0.468504 0.695482 0.356978 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'H']
updated_atom_counts [144, 144, 2]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/6_test/POSCAR.N2H_cent221
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [144, 144, 2, 1]
dummy number of surface atoms 288
mol_coords ['0.458334 0.682511 0.356978 T T T N\n', '0.387547 0.689320 0.361961 T T T N\n', '0.366524 0.690190 0.411552 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [144, 144, 2, 1]
Structure is Expanded
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/6_test/POSCAR.NH3_cent221
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [144, 144, 1, 3]
dummy number of surface atoms 288
mol_coords ['0.458334 0.682511 0.356978 T T T N\n', '0.410083 0.697797 0.375707 T T T H\n', '0.503088 0.701792 0.375732 T T T H\n', '0.461937 0.647912 0.375709 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [144, 144]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [144, 144, 1, 3]

In [32]:
mol_list = ['H2']

test_dir = './test_repeat_structure/0_VASP/SDA_test/1_test/'
surf_input = test_dir + 'POSCAR.surf'
surf_acf = test_dir + 'ACF_surf.dat'

for mol in mol_list:
    mol_atoms = atom_types(mol)
    mol_surf_dummy = test_dir + f'POSCAR.{mol}'
    expand_struct_vasp(surf_input, 
                    surf_input + '221',
                        [2,2,1])

    if len(mol_atoms) == 1:
        keep_central_2atmolecule(mol_surf_dummy,
                                [2,2,1],
                                 mol_atoms,
                                output_file= mol_surf_dummy + '_cent221')
    else:
        keep_central_3_4atmolecule(mol_surf_dummy,
                                 [2,2,1],
                                 mol_atoms,
                                  output_file= mol_surf_dummy + '_cent221')   

    add_molecule_to_surface(mol_surf_dummy + '_cent221',
                                surf_input + '221',
                                mol_surf_dummy + '_final',
                                mol_atoms)

Structure is Expanded
[336, 337, 338, 339, 340, 341, 342, 343]
Central molecule saved to ./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.H2_cent221
dummy species ['Pt', 'V', 'H']
dummy counts [296, 40, 2]
dummy number of surface atoms 336
mol_coords ['0.662379 0.671350 0.407636 T T T H\n', '0.681268 0.695282 0.407636 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [296, 40]
updated_species ['Pt', 'V', 'H']
updated_atom_counts [296, 40, 2]

In [33]:
#Done
def calculate_nearest_slab_distances_with_atom_info(poscar_file, molecule_atom_types, num_neighbor = 9):
    """
    Calculates the distances of the 9 nearest atoms in the slab from the molecule center.
    Includes the atom type, Cartesian coordinates, distance vector, distance magnitude, 
    and the order of each atom in the POSCAR file.

    Args:
        poscar_file (str): Path to the POSCAR file.
        molecule_atom_types (list): List of molecule atom types to identify (e.g., ['N', 'H']).
        num_neighbor (int): Number of nearest neighbors to return. Default is 9.

    Returns:
        dict: A dictionary containing:
            - 'molecule_center': Cartesian coordinates of the molecule center.
            - 'nearest_atoms': A list of the 9 nearest atoms with the following info:
                - Atom type (e.g., 'Pt', 'N').
                - Cartesian coordinates as a tuple.
                - Distance vector (relative position from molecule center).
                - Distance from the molecule center (magnitude of distance vector).
                - Atom order in the POSCAR file (0-based index).
    """
    import numpy as np
    from pymatgen.io.vasp import Poscar

    # Load POSCAR file and extract structure
    with open(poscar_file, "r") as f:
        file_content = f.read()  # Read file contents to ensure it's accessible

    poscar = Poscar.from_string(file_content)
    structure = poscar.structure

    # Convert fractional coordinates to Cartesian coordinates
    lattice_matrix = structure.lattice.matrix  # Lattice vectors (3x3 matrix)
    fractional_coords = structure.frac_coords  # Fractional coordinates of all atoms
    all_coords = np.dot(fractional_coords, lattice_matrix)  # Convert fractional to Cartesian
    all_atom_types = structure.species  # List of atom types

    # Filter molecule atoms by type
    molecule_coords = []
    molecule_indices = []
    for i, atom_type in enumerate(all_atom_types):
        if str(atom_type) in molecule_atom_types:
            molecule_coords.append(all_coords[i])
            molecule_indices.append(i)

    if len(molecule_coords) == 0:
        raise ValueError(f"No atoms of the specified types {molecule_atom_types} were found in the POSCAR file.")

    molecule_coords = np.array(molecule_coords)

    # Explicitly extract coordinates of N atoms
    nitrogen_coords = [
        all_coords[i] for i, atom in enumerate(all_atom_types) if str(atom) == "N"
    ]

    # Determine the molecule center based on the specified strategy
    if len(nitrogen_coords) == 2:
        # Two N atoms: Use the center of the two N atoms
        molecule_center = np.mean(nitrogen_coords, axis=0)
    elif len(nitrogen_coords) == 1:
        # One N atom: Use its coordinate
        molecule_center = nitrogen_coords[0]
    elif len(molecule_coords) == 2:
        # Biatomic molecule (not N₂): Use the center of the two atoms
        molecule_center = np.mean(molecule_coords, axis=0)
    else:
        # No N atoms or other multi-atom molecule: Use the center of all atoms
        molecule_center = np.mean(molecule_coords, axis=0)

    # Calculate distances from the molecule center to all slab atoms
    distances = []
    slab_atoms_info = []
    for i, coord in enumerate(all_coords):
        # Exclude distances between molecule atoms themselves
        if i in molecule_indices:
            continue
        distance_vector = coord - molecule_center  # Compute the distance vector
        distance = np.linalg.norm(distance_vector)  # Compute the magnitude of the distance vector
        distances.append(distance)
        slab_atoms_info.append((str(all_atom_types[i]), tuple(coord), tuple(distance_vector), distance, i))  # 0-based index

    # Sort by distance and select the nearest num_neighbor atoms
    sorted_atoms_info = sorted(slab_atoms_info, key=lambda x: x[3])[:num_neighbor]

    # Prepare results
    result = {
        "molecule_center": molecule_center.tolist(),
        "nearest_atoms": sorted_atoms_info  # Each entry contains (type, coordinates, distance vector, distance magnitude, index)
    }
    return result

In [34]:
#poscar_path = "./test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.H2" #Path to your POSCAR file
poscar_path = './test_repeat_structure/0_VASP/SDA_test/1_test/POSCAR.N2'
molecule_atom_types = ['N']

nearest_neighbors = calculate_nearest_slab_distances_with_atom_info(poscar_path, molecule_atom_types)

    
print("Molecule Center:", nearest_neighbors["molecule_center"])
print("Nearest Atoms:")
for atom_info in nearest_neighbors["nearest_atoms"]:
    atom_type, cart_coords, distance_vector, distance, index = atom_info
    print(f"Atom Type: {atom_type}, Coordinates: {cart_coords}, Distance Vector: {distance_vector}, Distance: {distance:.4f}, Index: {index}")

Molecule Center: [3.029476982326, 4.55092436129, 10.009467400633]
Nearest Atoms:
Atom Type: Pt, Coordinates: (3.0293248816219998, 4.507075888378001, 9.110537072088), Distance Vector: (-0.00015210070400017983, -0.043848472911999004, -0.8989303285449992), Distance: 0.9000, Index: 32
Atom Type: V, Coordinates: (4.408881208269001, 6.5491031860260005, 8.861883413339001), Distance Vector: (1.3794042259430013, 1.9981788247360006, -1.1475839872939986), Distance: 2.6856, Index: 79
Atom Type: Pt, Coordinates: (1.810991392582, 6.807587204494999, 9.131917774188), Distance Vector: (-1.218485589744, 2.2566628432049995, -0.8775496264449991), Distance: 2.7106, Index: 38
Atom Type: Pt, Coordinates: (5.786270698226, 4.504703040688, 9.116916771313), Distance Vector: (2.7567937158999998, -0.04622132060200013, -0.8925506293199987), Distance: 2.8981, Index: 33
Atom Type: Pt, Coordinates: (-0.001239820004, 4.782967095896, 9.047936796776), Distance Vector: (-3.0307168023299997, 0.2320427346059999, -0.9615306038569997), Distance: 3.1880, Index: 37
Atom Type: V, Coordinates: (4.4158840097239995, 4.948506003184, 6.985519431060999), Distance Vector: (1.3864070273979996, 0.3975816418939999, -3.023947969572), Distance: 3.3503, Index: 77
Atom Type: Pt, Coordinates: (1.591868035417, 4.974052086077, 6.917201136547), Distance Vector: (-1.4376089469089999, 0.4231277247870002, -3.0922662640859997), Distance: 3.4363, Index: 22
Atom Type: Pt, Coordinates: (3.04272814389, 2.677416623034, 7.0993106199269995), Distance Vector: (0.013251161563999858, -1.873507738256, -2.910156780706), Distance: 3.4611, Index: 16
Atom Type: Pt, Coordinates: (3.0300123300290003, 7.28390684422, 6.8882311549990005), Distance Vector: (0.000535347703000344, 2.73298248293, -3.121236245633999), Distance: 4.1487, Index: 31

In [35]:
#Done
def get_nearest_neighbors_with_bader_and_elneg(poscar_file, molecule_atom_types, acf_surf, poscar_surf, potcar_surf, supercell_size=[2,2,1], num_neighbor=9):
    """
    Finds the nearest neighbors of a molecule in a slab, retrieves their Bader charge, and calculates their electronegativity.

    Args:
        poscar_file (str): Path to the POSCAR file containing the slab and molecule (result from add_molecule func).
        molecule_atom_types (list): List of molecule atom types to identify (e.g., ['N', 'H']).
        acf_surf (str): Path to the unexpanded acf.dat file of the surface.
        poscar_surf (str): Path to the unexpanded POSCAR file of the surface.
        potcar_surf (str): Path to the POTCAR file of the surface.
        supercell_size (list, optional): Supercell expansion size. Default is [2,2,1].
        num_neighbor (int, optional): Number of nearest neighbors to find. Default is 9.

    Returns:
        dict: A dictionary containing:
            - 'molecule_center': Cartesian coordinates of the molecule center.
            - 'nearest_atoms': List of dictionaries for each nearest atom containing:
                - Atom type
                - Cartesian coordinates
                - Distance vector
                - Distance magnitude
                - Atom index in POSCAR
                - Bader charge
                - Electronegativity
    """
    import numpy as np

    # Step 1: Get nearest neighbors using the first function
    nearest_neighbors_data = calculate_nearest_slab_distances_with_atom_info(poscar_file, molecule_atom_types, num_neighbor)

    # Step 2: Expand charge file and get Bader charge data
    bader_df = expand_charge_file_VASP(acf_surf, poscar_surf, potcar_surf, supercell_size=supercell_size)

    # Step 3: Retrieve Bader charge and electronegativity for each nearest neighbor
    nearest_neighbors_with_extra_info = []
    
    for atom_info in nearest_neighbors_data["nearest_atoms"]:
        atom_type, cart_coords, distance_vector, distance, atom_index = atom_info

        # Fetch the Bader charge from the dataframe using the atom index
        try:
            bader_charge = bader_df.loc[atom_index, "bader_charge"]  # Adjust column name if needed
        except KeyError:
            bader_charge = None  # If index is not found, return None

        # Get the electronegativity for the atom type
        try:
            electronegativity = get_elneg(atom_type)
        except:
            electronegativity = None  # If not found, return None

        # Append all gathered info
        nearest_neighbors_with_extra_info.append({
            "atom_type": atom_type,
            "coordinates": cart_coords,
            "distance_vector": distance_vector,
            "distance": distance,
            "index": atom_index,
            "bader_charge": bader_charge,
            "electronegativity": electronegativity
        })

    # Step 4: Prepare final output dictionary
    result = {
        "molecule_center": nearest_neighbors_data["molecule_center"],
        "nearest_atoms": nearest_neighbors_with_extra_info
    }

    return result

In [36]:
# Define file paths
test_number = 2
poscar_file = f"./test_repeat_structure/0_VASP/SDA_test/{test_number}_test/POSCAR.N2_final"  # POSCAR file for the molecule
acf_surf = f"./test_repeat_structure/0_VASP/SDA_test/{test_number}_test/ACF_surf.dat"  # Bader charge file of the surface
poscar_surf = f"./test_repeat_structure/0_VASP/SDA_test/{test_number}_test/POSCAR.surf"  # POSCAR file of the surface
potcar_surf = f"./test_repeat_structure/0_VASP/SDA_test/{test_number}_test/POTCAR.surf"  # POTCAR file of the surface

# Define molecule atom types
molecule_atom_types = ["N",
                      #"H"
                      ]  # Example: Nitrogen and Hydrogen atoms

# Define supercell size
supercell_size = [2,2,1]  # Expanding in x2, y2, z1

# Define number of nearest neighbors
num_neighbors = 9

# Run the function
result = get_nearest_neighbors_with_bader_and_elneg(
    poscar_file=poscar_file,
    molecule_atom_types=molecule_atom_types,
    acf_surf=acf_surf,
    poscar_surf=poscar_surf,
    potcar_surf=potcar_surf,
    supercell_size=supercell_size,
    num_neighbor=num_neighbors
)

# Print results
print("\nMolecule Center:", result["molecule_center"])
print("\nNearest Atoms with Bader Charges and Electronegativity:")
for atom in result["nearest_atoms"]:
    print(f"Atom Type: {atom['atom_type']}")
    print(f"  Coordinates: {atom['coordinates']}")
    print(f"  Distance Vector: {atom['distance_vector']}")
    print(f"  Distance: {atom['distance']:.4f}")
    print(f"  Atom Index: {atom['index']}")
    print(f"  Bader Charge: {atom['bader_charge']}")
    print(f"  Electronegativity: {atom['electronegativity']}\n")
result

Molecule Center: [8.8763826438045, 12.416967730585, 7.716119081476]

Nearest Atoms with Bader Charges and Electronegativity:
Atom Type: Ni
  Coordinates: (8.876390837391, 12.41695501025, 6.816119322389)
  Distance Vector: (8.193586499061212e-06, -1.2720335000437899e-05, -0.8999997590869997)
  Distance: 0.9000
  Atom Index: 110
  Bader Charge: -0.22460000000000058
  Electronegativity: 1.91

Atom Type: Zn
  Coordinates: (10.241983125, 14.53631546527, 7.228378128166001)
  Distance Vector: (1.3656004811955, 2.1193477346850003, -0.48774095330999945)
  Distance: 2.5680
  Atom Index: 255
  Bader Charge: 0.15970000000000084
  Electronegativity: 1.65

Atom Type: Zn
  Coordinates: (7.510782162609, 14.53631546527, 7.228378128166001)
  Distance Vector: (-1.365600481195501, 2.1193477346850003, -0.48774095330999945)
  Distance: 2.5680
  Atom Index: 261
  Bader Charge: 0.15970000000000084
  Electronegativity: 1.65

Atom Type: Zn
  Coordinates: (10.241983125, 10.29619531838, 7.228378128166001)
  Distance Vector: (1.3656004811955, -2.1207724122049996, -0.48774095330999945)
  Distance: 2.5691
  Atom Index: 278
  Bader Charge: 0.1631999999999998
  Electronegativity: 1.65

Atom Type: Zn
  Coordinates: (7.510782162609, 10.29619531838, 7.228378128166001)
  Distance Vector: (-1.365600481195501, -2.1207724122049996, -0.48774095330999945)
  Distance: 2.5691
  Atom Index: 284
  Bader Charge: 0.1631999999999998
  Electronegativity: 1.65

Atom Type: Ni
  Coordinates: (11.607575412609, 12.41695501025, 6.816119322389)
  Distance Vector: (2.7311927688044992, -1.2720335000437899e-05, -0.8999997590869997)
  Distance: 2.8757
  Atom Index: 114
  Bader Charge: -0.22460000000000058
  Electronegativity: 1.91

Atom Type: Ni
  Coordinates: (6.145189875, 12.41695501025, 6.816119322389)
  Distance Vector: (-2.731192768804501, -1.2720335000437899e-05, -0.8999997590869997)
  Distance: 2.8757
  Atom Index: 116
  Bader Charge: -0.22460000000000058
  Electronegativity: 1.91

Atom Type: Zn
  Coordinates: (10.241983125, 12.36971168606, 4.781731346093)
  Distance Vector: (1.3656004811955, -0.04725604452499965, -2.934387735383)
  Distance: 3.2369
  Atom Index: 242
  Bader Charge: 0.22690000000000055
  Electronegativity: 1.65

Atom Type: Zn
  Coordinates: (7.510782162609, 12.36971168606, 4.781731346093)
  Distance Vector: (-1.365600481195501, -0.04725604452499965, -2.934387735383)
  Distance: 3.2369
  Atom Index: 248
  Bader Charge: 0.22690000000000055
  Electronegativity: 1.65

{'molecule_center': [8.8763826438045, 12.416967730585, 7.716119081476],
 'nearest_atoms': [{'atom_type': 'Ni',
   'coordinates': (8.876390837391, 12.41695501025, 6.816119322389),
   'distance_vector': (8.193586499061212e-06,
    -1.2720335000437899e-05,
    -0.8999997590869997),
   'distance': 0.8999997592141896,
   'index': 110,
   'bader_charge': -0.22460000000000058,
   'electronegativity': 1.91},
  {'atom_type': 'Zn',
   'coordinates': (10.241983125, 14.53631546527, 7.228378128166001),
   'distance_vector': (1.3656004811955,
    2.1193477346850003,
    -0.48774095330999945),
   'distance': 2.5679545814308264,
   'index': 255,
   'bader_charge': 0.15970000000000084,
   'electronegativity': 1.65},
  {'atom_type': 'Zn',
   'coordinates': (7.510782162609, 14.53631546527, 7.228378128166001),
   'distance_vector': (-1.365600481195501,
    2.1193477346850003,
    -0.48774095330999945),
   'distance': 2.567954581430827,
   'index': 261,
   'bader_charge': 0.15970000000000084,
   'electronegativity': 1.65},
  {'atom_type': 'Zn',
   'coordinates': (10.241983125, 10.29619531838, 7.228378128166001),
   'distance_vector': (1.3656004811955,
    -2.1207724122049996,
    -0.48774095330999945),
   'distance': 2.569130501968894,
   'index': 278,
   'bader_charge': 0.1631999999999998,
   'electronegativity': 1.65},
  {'atom_type': 'Zn',
   'coordinates': (7.510782162609, 10.29619531838, 7.228378128166001),
   'distance_vector': (-1.365600481195501,
    -2.1207724122049996,
    -0.48774095330999945),
   'distance': 2.5691305019688944,
   'index': 284,
   'bader_charge': 0.1631999999999998,
   'electronegativity': 1.65},
  {'atom_type': 'Ni',
   'coordinates': (11.607575412609, 12.41695501025, 6.816119322389),
   'distance_vector': (2.7311927688044992,
    -1.2720335000437899e-05,
    -0.8999997590869997),
   'distance': 2.875658795282996,
   'index': 114,
   'bader_charge': -0.22460000000000058,
   'electronegativity': 1.91},
  {'atom_type': 'Ni',
   'coordinates': (6.145189875, 12.41695501025, 6.816119322389),
   'distance_vector': (-2.731192768804501,
    -1.2720335000437899e-05,
    -0.8999997590869997),
   'distance': 2.8756587952829973,
   'index': 116,
   'bader_charge': -0.22460000000000058,
   'electronegativity': 1.91},
  {'atom_type': 'Zn',
   'coordinates': (10.241983125, 12.36971168606, 4.781731346093),
   'distance_vector': (1.3656004811955, -0.04725604452499965, -2.934387735383),
   'distance': 3.236932064401677,
   'index': 242,
   'bader_charge': 0.22690000000000055,
   'electronegativity': 1.65},
  {'atom_type': 'Zn',
   'coordinates': (7.510782162609, 12.36971168606, 4.781731346093),
   'distance_vector': (-1.365600481195501,
    -0.04725604452499965,
    -2.934387735383),
   'distance': 3.236932064401677,
   'index': 248,
   'bader_charge': 0.22690000000000055,
   'electronegativity': 1.65}]}

# OUTCAR Files

In [37]:
def extract_total_energy_from_outcar(outcar_file):
    """
    Extracts the last total energy (TOTEN) from a VASP OUTCAR file.

    Args:
        outcar_file (str): Path to the OUTCAR file.

    Returns:
        float: Last total energy in eV, or None if not found.
    """
    last_energy = None  # Initialize to None
    
    try:
        with open(outcar_file, "r") as f:
            for line in f:
                if "free  energy   TOTEN" in line:
                    last_energy = float(line.split()[-2])  # Extract the energy value

    except FileNotFoundError:
        print(f"Error: The file {outcar_file} does not exist.")
    except Exception as e:
        print(f"Error reading OUTCAR file: {e}")

    return last_energy  # Return the last found energy value

In [38]:
outcar_path = './test_repeat_structure/0_VASP/SDA_test_outcar/OUTCAR'
extract_total_energy_from_outcar(outcar_path)

-421.47162546

In [39]:
from pymatgen.io.vasp import Poscar
from pymatgen.core.structure import Structure

def calculate_molecule_distances(poscar_file, molecule_atoms):
    """
    Reads a CONTCAR file, extracts a molecular structure, and calculates distances between the molecule's atoms,
    considering periodic boundary conditions (PBC).

    Args:
        poscar_file (str): Path to the CONTCAR file.
        molecule_atoms (list): List of atomic symbols representing the molecule (e.g., ["N", "H"] for NH3).

    Returns:
        list: A sorted list of calculated distances based on the molecule type.
    """
    try:
        # Read CONTCAR file as a string
        with open(poscar_file, "r") as f:
            file_content = f.read()

        # Use Poscar.from_string() to parse the file content
        poscar = Poscar.from_string(file_content)
        structure = poscar.structure

        # Extract only molecule atoms
        molecule_sites = [site for site in structure.sites if site.species_string in molecule_atoms]

        if len(molecule_sites) < 2:
            raise ValueError("Molecule must have at least two atoms to compute distances.")

        distances = []

        if len(molecule_sites) == 2:
            # Biatomic case (e.g., N2, O2)
            distances.append(structure.lattice.get_distance_and_image(
                molecule_sites[0].frac_coords, molecule_sites[1].frac_coords
            )[0])

        elif len(molecule_sites) == 3:
            # Case: N2H (2N, 1H) → Find N-N and smallest N-H distance
            nitrogen_atoms = [site for site in molecule_sites if site.species_string == "N"]
            hydrogen_atoms = [site for site in molecule_sites if site.species_string == "H"]

            if len(nitrogen_atoms) == 2 and len(hydrogen_atoms) == 1:
                nn_distance = structure.lattice.get_distance_and_image(
                    nitrogen_atoms[0].frac_coords, nitrogen_atoms[1].frac_coords
                )[0]

                nh_distances = [
                    structure.lattice.get_distance_and_image(nitrogen.frac_coords, hydrogen_atoms[0].frac_coords)[0]
                    for nitrogen in nitrogen_atoms
                ]

                distances.append(nn_distance)
                distances.append(min(nh_distances))  # Choose the smallest N-H distance

        elif len(molecule_sites) == 4:
            # Case: NH3 (1N, 3H) → Compute 3 N-H distances and sort them
            nitrogen_atoms = [site for site in molecule_sites if site.species_string == "N"]
            hydrogen_atoms = [site for site in molecule_sites if site.species_string == "H"]

            if len(nitrogen_atoms) == 1 and len(hydrogen_atoms) == 3:
                nh_distances = [
                    structure.lattice.get_distance_and_image(nitrogen_atoms[0].frac_coords, h.frac_coords)[0]
                    for h in hydrogen_atoms
                ]

                distances.extend(sorted(nh_distances))  # Sort from smallest to largest

        return distances

    except Exception as e:
        print(f"Error processing CONTCAR file: {e}")
        return None

In [40]:
# Define the path to your CONTCAR file

# Example 0: Biatomic molecule (e.g., N2)
number_list = list(range(1,10))


molecule_atoms = ["N"]
for i in number_list:
    contcar_path = f'./test_repeat_structure/0_VASP/SDA_test_outcar/N2/CONTCAR.N2_{i}'
    distances = calculate_molecule_distances(contcar_path, molecule_atoms)
    print(f"N-N distance CONTCAR.N2_{i}:", distances)

# Example 1: Biatomic molecule (e.g., H2)
molecule_atoms = ["H"]
for i in number_list:
    contcar_path = f'./test_repeat_structure/0_VASP/SDA_test_outcar/H2/CONTCAR.H2_{i}'
    distances = calculate_molecule_distances(contcar_path, molecule_atoms)
    print(f"H-H distance CONTCAR.H2_{i}:", distances)

# Example 2: N2H molecule (2N, 1H)
molecule_atoms = ["N", "H"]
for i in number_list:
    contcar_path = f'./test_repeat_structure/0_VASP/SDA_test_outcar/N2H/CONTCAR.N2H_{i}'
    distances = calculate_molecule_distances(contcar_path, molecule_atoms)
    print(f"N-N and smaller N-H distance CONTCAR.N2H_{i}:", distances)

# Example 3: NH3 molecule (1N, 3H)
molecule_atoms = ["N", "H"]
for i in number_list:
    contcar_path = f'./test_repeat_structure/0_VASP/SDA_test_outcar/NH3/CONTCAR.NH3_{i}'
    distances = calculate_molecule_distances(contcar_path, molecule_atoms)
    print(f"Sorted N-H distances CONTCAR.NH3_{i}:", distances)

N-N distance CONTCAR.N2_1: [1.120982238881245]
N-N distance CONTCAR.N2_2: [4.850461155034299]
N-N distance CONTCAR.N2_3: [3.239021168379713]
N-N distance CONTCAR.N2_4: [3.991119522183379]
N-N distance CONTCAR.N2_5: [1.1209822388812458]
N-N distance CONTCAR.N2_6: [1.120982238881246]
N-N distance CONTCAR.N2_7: [7.511014953007913]
N-N distance CONTCAR.N2_8: [5.878624279688735]
N-N distance CONTCAR.N2_9: [1.1209822388812447]
H-H distance CONTCAR.H2_1: [0.7393934951642832]
H-H distance CONTCAR.H2_2: [4.125070970552226]
H-H distance CONTCAR.H2_3: [3.3032620850380603]
H-H distance CONTCAR.H2_4: [3.4054371245753647]
H-H distance CONTCAR.H2_5: [0.7393934951642832]
H-H distance CONTCAR.H2_6: [0.7393934951642832]
H-H distance CONTCAR.H2_7: [5.994769241221559]
H-H distance CONTCAR.H2_8: [4.009793909177997]
H-H distance CONTCAR.H2_9: [0.7393934951642829]
N-N and smaller N-H distance CONTCAR.N2H_1: [1.1779757259171637, 1.1443160199114117]
N-N and smaller N-H distance CONTCAR.N2H_2: [2.659247116164248, 3.1892155519569747]
N-N and smaller N-H distance CONTCAR.N2H_3: [1.1779757259171637, 3.41149271224004]
N-N and smaller N-H distance CONTCAR.N2H_4: [1.1779757259171635, 5.242520343822926]
N-N and smaller N-H distance CONTCAR.N2H_5: [1.177975725917164, 1.1443160199114115]
N-N and smaller N-H distance CONTCAR.N2H_6: [1.1779757259171628, 1.1443160199114133]
N-N and smaller N-H distance CONTCAR.N2H_7: [1.1779757259171637, 7.73110526498179]
N-N and smaller N-H distance CONTCAR.N2H_8: [1.1779757259171644, 3.1335596019301555]
N-N and smaller N-H distance CONTCAR.N2H_9: [1.1779757259171637, 1.1443160199114113]
Sorted N-H distances CONTCAR.NH3_1: [0.9727321759968955, 0.9736869279174211, 0.9740208513720635]
Sorted N-H distances CONTCAR.NH3_2: [0.9736869279174215, 4.564464850422038, 5.364988339249033]
Sorted N-H distances CONTCAR.NH3_3: [0.9736869279174206, 5.2795488060392834, 5.730755482649761]
Sorted N-H distances CONTCAR.NH3_4: [1.0737026752485181, 3.044031229528533, 6.585694441012466]
Sorted N-H distances CONTCAR.NH3_5: [0.9727321759968951, 0.9736869279174211, 0.974020851372064]
Sorted N-H distances CONTCAR.NH3_6: [0.9727321759968944, 0.9736869279174211, 0.9740208513720653]
Sorted N-H distances CONTCAR.NH3_7: [0.9736869279174207, 4.2659507309314595, 7.402106803533126]
Sorted N-H distances CONTCAR.NH3_8: [0.974020851372064, 3.552602835247314, 7.340012903449902]
Sorted N-H distances CONTCAR.NH3_9: [0.9727321759968953, 0.9736869279174211, 0.9740208513720638]

In [41]:
#Dont forget for each poscar H2 N2 consider the electronegativity of molecule atoms 
# Do some testing on the merged function
# Find out the status of mol in outcar: distances of mol atoms from each other, distance from surface

In [42]:
def outcar_converged(outcar_file):
    """
    Reads an OUTCAR file, checks if the convergence criteria is met.

    Args:
        outcar_file (str): Path to the CONTCAR file.

    Returns:
        int: A value of 0 (not converged structure) or 1 (converged).
    """
    converged = 0
    with open(outcar_file, "r") as f:
        outcar_lines = f.readlines()
    for line in outcar_lines:
        if 'reached required accuracy - stopping structural energy minimisation' in line:
            converged = converged + 1
    return converged

In [43]:
outcar_converged('./test_repeat_structure/0_VASP/SDA_test_outcar/OUTCAR')

1

# Copying the files ready

#Here I just want to copy files before doing any more changes to them or data extraction
import os
import shutil

Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

person ='Satvik'
if person == 'Subhmoy':
    used_materials = Subhmoy_materials
if person == 'Satvik':
    used_materials = Satvik_materials
    

destination = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'

for i in range(len(used_materials)):
    material = str(i) + '_' + used_materials[i]
    os.mkdir(destination + material)
    os.mkdir(destination + f"{material}/1_surf/")
    os.mkdir(destination + f"{material}/2_N2/")
    os.mkdir(destination + f"{material}/3_H2/")
    os.mkdir(destination + f"{material}/4_N2H/")
    os.mkdir(destination + f"{material}/5_NH3/")

In [8]:
#Copy bader files
import os
import shutil
Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

person ='Subhmoy'
if person == 'Subhmoy':
    used_materials = Subhmoy_materials
if person == 'Satvik':
    used_materials = Satvik_materials
    
origin_bader = f'/run/user/1001/gvfs/smb-share:server=10.50.16.153,share=data-iml/Parastoo/big_ad_sites_project/scf_bader_DOS_surf/{person}/'
destination = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'

for i in range(len(used_materials)):
    material = str(i) + '_' + used_materials[i]
    origin_mat_path = origin_bader + f'{material}/1_surf/postprocess/1_bader/ACF.dat'
    dest_mat_path = destination + f'{material}/1_surf/'
    if os.path.exists(origin_mat_path):
        shutil.copy(origin_mat_path, dest_mat_path)
    else:
        print(f'File {person}/{material}/ACF.dat does NOT exist')

#Copy surf_CONTCAR and surf_POTCAR files
Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

origin_files = ['OUTCAR','CONTCAR','POTCAR']
dest_files = ['OUTCAR.surf','POSCAR.surf','POTCAR.surf']

persons =['Subhmoy','Satvik']
for person in persons:
    if person == 'Subhmoy':
        used_materials = Subhmoy_materials
    if person == 'Satvik':
        used_materials = Satvik_materials

    origin_surf = f'/run/user/1001/gvfs/smb-share:server=10.50.16.153,share=data-iml/Shared_ML/{person}_cedar/'
    destination = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'

    for file_ind in range(len(origin_files)):
        file_origin = origin_files[file_ind]
        file_dest = dest_files[file_ind]
        for i in range(len(used_materials)):
            material = str(i) + '_' + used_materials[i]
            origin_mat_path = origin_surf + f'{material}/1_surf/{file_origin}' #or CONTCAR
            dest_mat_path = destination + f'{material}/1_surf/{file_dest}' #or POSCAR.surf
            if os.path.exists(origin_mat_path):
                shutil.copy(origin_mat_path, dest_mat_path)
            else:
                print(f'File {person}/{material}/POTCAR does NOT exist')

In [48]:
#Copy adsorption files
#working on now
import os
import shutil

Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

person ='Satvik'
if person == 'Subhmoy':
    used_materials = Subhmoy_materials
if person == 'Satvik':
    used_materials = Satvik_materials
    
copy_files = ['CONTCAR','POSCAR_initial', 'OUTCAR']
    

destination = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'

origin = f'/run/user/1001/gvfs/smb-share:server=10.50.16.153,share=data-iml/Shared_ML/{person}_cedar/'

def poscar_initial_origin(mol, person, material, adnum):
    if mol == '2_N2' or mol == '3_H2':
        return f'/home/parastoo/Desktop/ML_project/{person}/{material}/{mol}/{adnum}/'
    
    elif mol == '4_N2H':
        return f'/home/parastoo/Desktop/ML_project/N2H/{person}/{material}/{mol}/{adnum}/'
    
    elif mol == '5_NH3':
        return f'/home/parastoo/Desktop/ML_project/NH3/{person}/{material}/{mol}/{adnum}/'
    
    

for i in range(len(used_materials)):
#for i in range(0,1):
    material = str(i) + '_' + used_materials[i]
    material_origin_dir = origin + f"{material}/"
    #for m in range(len(mols)):
    #for m in range(0,4):
    for m in range(3,4):
        mol = str(m+2) + '_' + mols[m]
        mol_dir = material_origin_dir + f'{mol}/'
        if os.path.isdir(mol_dir):
            ad_sites_dirs = []
            for each_dir in os.listdir(mol_dir):
                if 'ad_site' in each_dir:
                    ad_sites_dirs.append(each_dir)
            ad_sites_dirs = sorted(ad_sites_dirs,key=lambda x: int(re.findall(r'\d+', x)[0]))
            for ad_site_num in ad_sites_dirs:
                ad_site_path = mol_dir + f'{ad_site_num}/'
                outcar_adsite_path = ad_site_path + 'OUTCAR'
                contcar_adsite_path = ad_site_path + 'CONTCAR'
                if os.path.exists(outcar_adsite_path) and outcar_converged(outcar_adsite_path):
                    os.makedirs(destination + f'{material}/{mol}/{ad_site_num}/',exist_ok=True)
                    shutil.copy(ad_site_path + 'OUTCAR',destination + f'{material}/{mol}/{ad_site_num}/')
                    if os.path.exists(contcar_adsite_path):
                        shutil.copy(ad_site_path + 'CONTCAR',destination + f'{material}/{mol}/{ad_site_num}/')
                    else:
                        print(f'CONTCAR does not exist:   {contcar_adsite_path}')
                    if os.path.exists(ad_site_path + 'POSCAR_initial'):
                        shutil.copy(ad_site_path + 'POSCAR_initial',destination + f'{material}/{mol}/{ad_site_num}/')
                    else:
                        poscar_initial_path = poscar_initial_origin(mol, person, material, ad_site_num) + 'POSCAR_initial'
                        shutil.copy(poscar_initial_path, destination + f'{material}/{mol}/{ad_site_num}/')
                            
            
            
        else:
            f'{person}/{material}/{mol_dir} does NOT exist'

#Compare if the files are copied properly
import filecmp
ad_site_nums = list(range(1,10))
destination = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/2_N2/'
origin =f'/run/user/1001/gvfs/smb-share:server=10.50.16.153,share=data-iml/Shared_ML/Subhmoy_cedar/0_Co3Ni/2_N2/'
copy_files = ['CONTCAR','POSCAR_initial', 'OUTCAR']

for site_num in ad_site_nums:
    adsite_dir_name = f'{site_num}_ad_site/'
    if os.path.exists(destination + adsite_dir_name):
        for each_file in copy_files:
            comparison = filecmp.cmp(destination + adsite_dir_name + each_file, origin + adsite_dir_name + each_file)
            if comparison:
                #print(f"{adsite_dir_name}/{each_file} are identical in both folders.") 
                continue
            else:
                print(f"{adsite_dir_name}/{each_file} are NOT identical in both folders.")

# Expansions

#We want to do the expansions of POSCAR of pristine surfaces
import os
import shutil

Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

person ='Subhmoy'
if person == 'Subhmoy':
    used_materials = Subhmoy_materials
if person == 'Satvik':
    used_materials = Satvik_materials
    
origin = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'

for i in range(len(used_materials)):
#for i in range(0,1):
    material = str(i) + '_' + used_materials[i]
    material_origin_dir = origin + f"{material}/"
    material_surf = material_origin_dir + '1_surf/'
    expand_struct_vasp(material_surf + 'POSCAR.surf',
                       material_surf + 'POSCAR.surf441',
                       [4,4,1])

In [50]:
#We want to do the expansions of mol+surface POSCAR initial ones
import os
import shutil

Subhmoy_materials_str = 'Co3Ni  CoPt3  CuPt   Fe3Co   FeCo  FeNi3  FePt3  NiPt VPt   VPt3  Zn11Co2  Zn13Co  Zn22Ni3 Zn3Cu  Zn8Cu5  ZnCu  ZnPt Co3Pt  Cu3Pt  CuPt7  Fe9Co7  FeNi  FePt   Ni3Pt  NiPt3  V3Pt VPt2  VPt8  Zn11Ni2  Zn13Fe  Zn35Cu17  Zn3Pt  Zn9Fe4  ZnNi  ZnPt3'
Subhmoy_materials = Subhmoy_materials_str.split()

Satvik_materials_str = 'Al13Fe4  Al3Ni   Al3Pt5  Al5Co2  AlCu3  AlNi3  AlV   V3Ni   VFe3 Al21Pt8  Al3Ni2  Al3V    Al9Co2   AlFe   AlPt   AlV3  V3Ni2  VNi2 Al2Cu    Al3Ni5  Al4Cu9  AlCo    AlFe3  AlPt2  V3Co  V4Zn5  VNi3 Al2Pt    Al3Pt2  Al4Ni3  AlCu    AlNi   AlPt3  V3Fe  VCo3   VZn3'
Satvik_materials = Satvik_materials_str.split()

mols = ['N2','H2','N2H','NH3']

mols_dict = {'N2':['N'],
            'H2':['H'],
            'N2H':['N','H'],
            'NH3':['N','H'],}

person ='Subhmoy'
if person == 'Subhmoy':
    used_materials = Subhmoy_materials
if person == 'Satvik':
    used_materials = Satvik_materials
    
origin = f'/home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/{person}/'



for i in range(len(used_materials)):
#for i in range(0,1):
    material = str(i) + '_' + used_materials[i]
    material_origin_dir = origin + f"{material}/"
    surf_input = material_origin_dir + '1_surf/POSCAR.surf441'
    #for m in range(len(mols)):
    for m in range(3,4):
        mol_atom_type =  mols_dict[mols[m]]
        mol = str(m+2) + '_' + mols[m]
        mol_dir = material_origin_dir + f'{mol}/'
        if len(os.listdir(mol_dir)) > 0:
            ad_sites_dirs = []
            for each_dir in os.listdir(mol_dir):
                if 'ad_site' in each_dir:
                    ad_sites_dirs.append(each_dir)
            ad_sites_dirs = sorted(ad_sites_dirs,key=lambda x: int(re.findall(r'\d+', x)[0]))
            for ad_site_num in ad_sites_dirs:
                ad_site_path = mol_dir + f'{ad_site_num}/'
                if len(mol_atom_type) == 1:
                    keep_central_2atmolecule(ad_site_path + 'POSCAR_initial',
                                            [4,4,1],
                                             mol_atom_type,
                                            output_file= ad_site_path + 'POSCAR_initial' + '_cent441')
                else:
                    keep_central_3_4atmolecule(ad_site_path + 'POSCAR_initial',
                                            [4,4,1],
                                             mol_atom_type,
                                            output_file= ad_site_path + 'POSCAR_initial' + '_cent441')   

                add_molecule_to_surface(ad_site_path + 'POSCAR_initial' + '_cent441',
                                            surf_input,
                                            ad_site_path + 'POSCAR_initial' + '_final441',
                                            mol_atom_type)

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.521353 0.510747 0.384611 T T T N\n', '0.507014 0.522120 0.402525 T T T H\n', '0.547100 0.525092 0.402549 T T T H\n', '0.509977 0.485005 0.402528 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.520787 0.572963 0.385570 T T T N\n', '0.506447 0.584337 0.403484 T T T H\n', '0.546534 0.587309 0.403508 T T T H\n', '0.509411 0.547222 0.403486 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.583003 0.479072 0.384611 T T T N\n', '0.568665 0.490446 0.402525 T T T H\n', '0.608751 0.493418 0.402549 T T T H\n', '0.571628 0.453330 0.402528 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.551895 0.572681 0.385090 T T T N\n', '0.537556 0.584054 0.403004 T T T H\n', '0.577642 0.587026 0.403029 T T T H\n', '0.540520 0.546938 0.403007 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.552178 0.385747 0.384611 T T T N\n', '0.537839 0.397120 0.402525 T T T H\n', '0.577925 0.400092 0.402549 T T T H\n', '0.540802 0.360005 0.402528 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.604120 0.489630 0.384611 T T T N\n', '0.589781 0.501004 0.402525 T T T H\n', '0.629867 0.503976 0.402549 T T T H\n', '0.592744 0.463888 0.402528 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.562265 0.593703 0.384931 T T T N\n', '0.547926 0.605076 0.402845 T T T H\n', '0.588012 0.608048 0.402869 T T T H\n', '0.550889 0.567961 0.402847 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.541714 0.489819 0.384931 T T T N\n', '0.527375 0.501193 0.402845 T T T H\n', '0.567462 0.504165 0.402869 T T T H\n', '0.530339 0.464077 0.402847 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/0_Co3Ni/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Ni', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.437453 0.406297 0.384611 T T T N\n', '0.423114 0.417671 0.402525 T T T H\n', '0.463201 0.420642 0.402549 T T T H\n', '0.426078 0.380555 0.402528 T T T H\n']
main_species ['Co', 'Ni']
main_atom_counts [768, 256]
updated_species ['Co', 'Ni', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.442430 0.573192 0.392497 T T T N\n', '0.429409 0.583521 0.410411 T T T H\n', '0.465812 0.586220 0.410436 T T T H\n', '0.432100 0.549815 0.410414 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.005485 0.541804 0.391723 T T T N\n', '0.992463 0.552133 0.409637 T T T H\n', '0.028867 0.554832 0.409661 T T T H\n', '0.995154 0.518427 0.409640 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.474096 0.541528 0.392497 T T T N\n', '0.461075 0.551856 0.410411 T T T H\n', '0.497478 0.554555 0.410435 T T T H\n', '0.463766 0.518151 0.410413 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.411597 0.604027 0.392496 T T T N\n', '0.398575 0.614356 0.410410 T T T H\n', '0.434979 0.617055 0.410435 T T T H\n', '0.401266 0.580650 0.410413 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.484467 0.531157 0.391980 T T T N\n', '0.471445 0.541486 0.409895 T T T H\n', '0.507849 0.544185 0.409919 T T T H\n', '0.474137 0.507780 0.409897 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.463541 0.552082 0.392497 T T T N\n', '0.450519 0.562411 0.410411 T T T H\n', '0.486923 0.565110 0.410435 T T T H\n', '0.453211 0.528706 0.410414 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.401134 0.614490 0.391980 T T T N\n', '0.388112 0.624819 0.409894 T T T H\n', '0.424516 0.627518 0.409918 T T T H\n', '0.390803 0.591113 0.409897 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/1_CoPt3/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.421875 0.468749 0.392498 T T T N\n', '0.408853 0.479078 0.410412 T T T H\n', '0.445257 0.481777 0.410436 T T T H\n', '0.411544 0.445373 0.410414 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [256, 768]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/2_CuPt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [1024, 768, 1, 3]
dummy number of surface atoms 1792
mol_coords ['0.005208 0.510417 0.358279 T T T N\n', '0.996136 0.517613 0.377007 T T T H\n', '0.021500 0.519494 0.377032 T T T H\n', '0.998011 0.494129 0.377010 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [1024, 768]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [1024, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/2_CuPt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [1024, 768, 1, 3]
dummy number of surface atoms 1792
mol_coords ['0.598958 0.572917 0.358279 T T T N\n', '0.589885 0.580113 0.377007 T T T H\n', '0.615250 0.581994 0.377032 T T T H\n', '0.591761 0.556629 0.377010 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [1024, 768]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [1024, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/2_CuPt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [1024, 768, 1, 3]
dummy number of surface atoms 1792
mol_coords ['0.609375 0.593750 0.358279 T T T N\n', '0.600302 0.600947 0.377007 T T T H\n', '0.625666 0.602827 0.377032 T T T H\n', '0.602177 0.577462 0.377010 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [1024, 768]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [1024, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.500000 0.437500 0.381428 T T T N\n', '0.476860 0.445518 0.399342 T T T H\n', '0.521463 0.447614 0.399366 T T T H\n', '0.501728 0.419352 0.399344 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375000 0.479167 0.386897 T T T N\n', '0.351860 0.487185 0.404811 T T T H\n', '0.396463 0.489281 0.404835 T T T H\n', '0.376728 0.461019 0.404813 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.395833 0.625000 0.384162 T T T N\n', '0.372694 0.633019 0.402076 T T T H\n', '0.417296 0.635114 0.402100 T T T H\n', '0.397561 0.606852 0.402079 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375000 0.604167 0.381428 T T T N\n', '0.351860 0.612185 0.399342 T T T H\n', '0.396463 0.614281 0.399366 T T T H\n', '0.376728 0.586018 0.399345 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.500000 0.395833 0.386896 T T T N\n', '0.476860 0.403852 0.404810 T T T H\n', '0.521463 0.405947 0.404834 T T T H\n', '0.501728 0.377685 0.404813 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375000 0.618056 0.383251 T T T N\n', '0.351860 0.626074 0.401165 T T T H\n', '0.396463 0.628170 0.401189 T T T H\n', '0.376728 0.599908 0.401167 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/3_Fe3Co/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [288, 864, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.500000 0.381945 0.385074 T T T N\n', '0.476860 0.389963 0.402988 T T T H\n', '0.521463 0.392058 0.403012 T T T H\n', '0.501728 0.363796 0.402990 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [288, 864]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [288, 864, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.520834 0.583335 0.459586 T T T N\n', '0.497536 0.591438 0.483823 T T T H\n', '0.542444 0.593555 0.483855 T T T H\n', '0.522574 0.564995 0.483826 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562501 0.625002 0.465755 T T T N\n', '0.539202 0.633105 0.489992 T T T H\n', '0.584110 0.635222 0.490025 T T T H\n', '0.564240 0.606662 0.489996 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.520834 0.458334 0.465757 T T T N\n', '0.497536 0.466438 0.489994 T T T H\n', '0.542444 0.468555 0.490027 T T T H\n', '0.522574 0.439995 0.489998 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.500000 0.437501 0.462675 T T T N\n', '0.476702 0.445604 0.486912 T T T H\n', '0.521610 0.447722 0.486945 T T T H\n', '0.501741 0.419161 0.486916 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562500 0.416668 0.459594 T T T N\n', '0.539202 0.424771 0.483831 T T T H\n', '0.584110 0.426888 0.483864 T T T H\n', '0.564240 0.398328 0.483835 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.520834 0.444446 0.463703 T T T N\n', '0.497535 0.452549 0.487939 T T T H\n', '0.542444 0.454666 0.487972 T T T H\n', '0.522574 0.426106 0.487943 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/4_FeCo/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562500 0.430557 0.461649 T T T N\n', '0.539202 0.438660 0.485886 T T T H\n', '0.584110 0.440777 0.485918 T T T H\n', '0.564240 0.412217 0.485889 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [576, 576]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.390615 0.500008 0.387699 T T T N\n', '0.365278 0.511216 0.405613 T T T H\n', '0.401850 0.514144 0.405637 T T T H\n', '0.404772 0.474642 0.405616 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.390947 0.437333 0.387440 T T T N\n', '0.365610 0.448541 0.405355 T T T H\n', '0.402182 0.451469 0.405379 T T T H\n', '0.405103 0.411967 0.405357 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.577931 0.468838 0.387440 T T T N\n', '0.552594 0.480045 0.405354 T T T H\n', '0.589166 0.482974 0.405379 T T T H\n', '0.592087 0.443472 0.405357 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.515782 0.468670 0.387569 T T T N\n', '0.490445 0.479878 0.405483 T T T H\n', '0.527017 0.482806 0.405507 T T T H\n', '0.529938 0.443304 0.405486 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.546938 0.437332 0.387438 T T T N\n', '0.521601 0.448539 0.405352 T T T H\n', '0.558174 0.451468 0.405376 T T T H\n', '0.561095 0.411966 0.405354 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.598936 0.458336 0.387440 T T T N\n', '0.573599 0.469544 0.405355 T T T H\n', '0.610172 0.472472 0.405379 T T T H\n', '0.613093 0.432970 0.405357 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.536497 0.458224 0.387525 T T T N\n', '0.511160 0.469431 0.405439 T T T H\n', '0.547733 0.472360 0.405463 T T T H\n', '0.550654 0.432858 0.405441 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.432270 0.541669 0.387438 T T T N\n', '0.406933 0.552877 0.405353 T T T H\n', '0.443505 0.555806 0.405377 T T T H\n', '0.446427 0.516303 0.405355 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/5_FeNi3/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.432159 0.604228 0.387525 T T T N\n', '0.406822 0.615435 0.405440 T T T H\n', '0.443394 0.618364 0.405464 T T T H\n', '0.446316 0.578862 0.405442 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [256, 768]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.489585 0.385416 0.389948 T T T N\n', '0.476669 0.395660 0.407862 T T T H\n', '0.512776 0.398338 0.407886 T T T H\n', '0.479339 0.362229 0.407864 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.551747 0.509737 0.392180 T T T N\n', '0.538831 0.519981 0.410094 T T T H\n', '0.574939 0.522658 0.410118 T T T H\n', '0.541500 0.486550 0.410096 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.583505 0.541495 0.392181 T T T N\n', '0.570589 0.551740 0.410095 T T T H\n', '0.606697 0.554417 0.410119 T T T H\n', '0.573259 0.518308 0.410097 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.520666 0.510076 0.391059 T T T N\n', '0.507750 0.520321 0.408973 T T T H\n', '0.543857 0.522998 0.408998 T T T H\n', '0.510419 0.486889 0.408976 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.521004 0.573255 0.392180 T T T N\n', '0.508089 0.583500 0.410094 T T T H\n', '0.544196 0.586177 0.410119 T T T H\n', '0.510758 0.550068 0.410097 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.572918 0.552082 0.392180 T T T N\n', '0.560003 0.562327 0.410095 T T T H\n', '0.596110 0.565004 0.410119 T T T H\n', '0.562672 0.528895 0.410097 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.510531 0.552308 0.391433 T T T N\n', '0.497616 0.562553 0.409347 T T T H\n', '0.533723 0.565230 0.409371 T T T H\n', '0.500285 0.529122 0.409350 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.531025 0.531136 0.391433 T T T N\n', '0.518110 0.541380 0.409347 T T T H\n', '0.554217 0.544057 0.409371 T T T H\n', '0.520779 0.507949 0.409350 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/6_FePt3/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.531252 0.593749 0.392181 T T T N\n', '0.518336 0.603994 0.410095 T T T H\n', '0.554444 0.606671 0.410119 T T T H\n', '0.521006 0.570562 0.410098 T T T H\n']
main_species ['Fe', 'Pt']
main_atom_counts [256, 768]
updated_species ['Fe', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/7_NiPt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.416662 0.583367 0.388127 T T T N\n', '0.393898 0.591025 0.406144 T T T H\n', '0.437777 0.593025 0.406169 T T T H\n', '0.418362 0.566049 0.406147 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [576, 576]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/7_NiPt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375002 0.416834 0.388106 T T T N\n', '0.352237 0.424492 0.406123 T T T H\n', '0.396116 0.426492 0.406148 T T T H\n', '0.376701 0.399516 0.406126 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [576, 576]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/7_NiPt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.583336 0.375067 0.386867 T T T N\n', '0.560572 0.382726 0.404884 T T T H\n', '0.604451 0.384726 0.404908 T T T H\n', '0.585036 0.357749 0.404887 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [576, 576]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/7_NiPt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375002 0.402913 0.387694 T T T N\n', '0.352238 0.410571 0.405710 T T T H\n', '0.396117 0.412571 0.405735 T T T H\n', '0.376702 0.385595 0.405713 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [576, 576]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/7_NiPt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.583341 0.611167 0.387290 T T T N\n', '0.560577 0.618826 0.405307 T T T H\n', '0.604455 0.620826 0.405332 T T T H\n', '0.585040 0.593850 0.405310 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [576, 576]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/8_VPt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [432, 288, 1, 3]
dummy number of surface atoms 720
mol_coords ['0.583337 0.604164 0.375654 T T T N\n', '0.559236 0.616018 0.393568 T T T H\n', '0.605691 0.619115 0.393592 T T T H\n', '0.585137 0.577334 0.393571 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [432, 288]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [432, 288, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/8_VPt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [432, 288, 1, 3]
dummy number of surface atoms 720
mol_coords ['0.416669 0.479164 0.375653 T T T N\n', '0.392569 0.491018 0.393568 T T T H\n', '0.439023 0.494115 0.393592 T T T H\n', '0.418469 0.452334 0.393570 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [432, 288]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [432, 288, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/8_VPt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [432, 288, 1, 3]
dummy number of surface atoms 720
mol_coords ['0.458334 0.479166 0.375651 T T T N\n', '0.434233 0.491020 0.393566 T T T H\n', '0.480688 0.494118 0.393590 T T T H\n', '0.460133 0.452337 0.393568 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [432, 288]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [432, 288, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/8_VPt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [432, 288, 1, 3]
dummy number of surface atoms 720
mol_coords ['0.444446 0.465276 0.375649 T T T N\n', '0.420346 0.477130 0.393564 T T T H\n', '0.466801 0.480227 0.393588 T T T H\n', '0.446246 0.438446 0.393566 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [432, 288]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [432, 288, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.378121 0.546721 0.407749 T T T N\n', '0.356048 0.554398 0.424917 T T T H\n', '0.398596 0.556404 0.424940 T T T H\n', '0.379770 0.529345 0.424919 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.513160 0.501499 0.402099 T T T N\n', '0.491086 0.509176 0.419266 T T T H\n', '0.533634 0.511182 0.419289 T T T H\n', '0.514808 0.484123 0.419269 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.508140 0.461610 0.404924 T T T N\n', '0.486067 0.469287 0.422092 T T T H\n', '0.528615 0.471293 0.422115 T T T H\n', '0.509789 0.444234 0.422094 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.570640 0.444331 0.404924 T T T N\n', '0.548567 0.452008 0.422092 T T T H\n', '0.591115 0.454015 0.422115 T T T H\n', '0.572289 0.426956 0.422094 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.575660 0.484221 0.402099 T T T N\n', '0.553586 0.491898 0.419266 T T T H\n', '0.596134 0.493904 0.419289 T T T H\n', '0.577308 0.466845 0.419269 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.388160 0.421720 0.402099 T T T N\n', '0.366086 0.429398 0.419266 T T T H\n', '0.408634 0.431404 0.419289 T T T H\n', '0.389808 0.404345 0.419269 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.570640 0.524110 0.404924 T T T N\n', '0.548567 0.531787 0.422092 T T T H\n', '0.591115 0.533793 0.422115 T T T H\n', '0.572289 0.506734 0.422094 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.551480 0.463387 0.403982 T T T N\n', '0.529407 0.471064 0.421150 T T T H\n', '0.571954 0.473071 0.421173 T T T H\n', '0.553129 0.446012 0.421152 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.593147 0.421720 0.403982 T T T N\n', '0.571073 0.429398 0.421150 T T T H\n', '0.613621 0.431404 0.421173 T T T H\n', '0.594795 0.404345 0.421152 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.593147 0.505054 0.403982 T T T N\n', '0.571073 0.512731 0.421150 T T T H\n', '0.613621 0.514737 0.421173 T T T H\n', '0.594795 0.487678 0.421152 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/10_Zn11Co2/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Zn', 'N', 'H']
dummy counts [160, 1024, 1, 3]
dummy number of surface atoms 1184
mol_coords ['0.426480 0.421720 0.403982 T T T N\n', '0.404407 0.429398 0.421150 T T T H\n', '0.446954 0.431404 0.421173 T T T H\n', '0.428129 0.404345 0.421152 T T T H\n']
main_species ['Co', 'Zn']
main_atom_counts [160, 1024]
updated_species ['Co', 'Zn', 'N', 'H']
updated_atom_counts [160, 1024, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.499380 0.500621 0.417835 T T T N\n', '0.486357 0.510949 0.435003 T T T H\n', '0.522763 0.513648 0.435026 T T T H\n', '0.489049 0.477243 0.435006 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.499628 0.563245 0.421488 T T T N\n', '0.486605 0.573573 0.438655 T T T H\n', '0.523011 0.576272 0.438678 T T T H\n', '0.489297 0.539867 0.438658 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.436756 0.594309 0.421488 T T T N\n', '0.423734 0.604638 0.438655 T T T H\n', '0.460139 0.607336 0.438678 T T T H\n', '0.426425 0.570931 0.438658 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.468192 0.531809 0.421488 T T T N\n', '0.455170 0.542137 0.438655 T T T H\n', '0.491575 0.544837 0.438678 T T T H\n', '0.457861 0.508431 0.438658 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.624503 0.469432 0.419661 T T T N\n', '0.611482 0.479762 0.436829 T T T H\n', '0.647887 0.482460 0.436852 T T T H\n', '0.614173 0.446055 0.436832 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.416046 0.583954 0.421488 T T T N\n', '0.403024 0.594283 0.438655 T T T H\n', '0.439429 0.596982 0.438678 T T T H\n', '0.405716 0.560576 0.438658 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.457713 0.542287 0.421488 T T T N\n', '0.444691 0.552616 0.438655 T T T H\n', '0.481096 0.555315 0.438678 T T T H\n', '0.447382 0.518910 0.438658 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.603587 0.459037 0.420270 T T T N\n', '0.590565 0.469366 0.437438 T T T H\n', '0.626970 0.472064 0.437461 T T T H\n', '0.593257 0.435659 0.437440 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/13_Zn3Cu/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [320, 960, 1, 3]
dummy number of surface atoms 1280
mol_coords ['0.457630 0.479746 0.420270 T T T N\n', '0.444608 0.490075 0.437438 T T T H\n', '0.481013 0.492774 0.437461 T T T H\n', '0.447300 0.456368 0.437440 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [320, 960]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [320, 960, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.531555 0.541069 0.028149 T T T N\n', '0.509231 0.548834 0.046064 T T T H\n', '0.552262 0.550863 0.046088 T T T H\n', '0.533222 0.523496 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.469055 0.562500 0.028149 T T T N\n', '0.446730 0.570265 0.046064 T T T H\n', '0.489762 0.572293 0.046088 T T T H\n', '0.470722 0.544927 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.531555 0.625000 0.028149 T T T N\n', '0.509231 0.632765 0.046064 T T T H\n', '0.552262 0.634793 0.046088 T T T H\n', '0.533222 0.607427 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.594055 0.396431 0.028149 T T T N\n', '0.571731 0.404195 0.046064 T T T H\n', '0.614762 0.406224 0.046088 T T T H\n', '0.595722 0.378858 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.406555 0.625000 0.028149 T T T N\n', '0.384230 0.632765 0.046064 T T T H\n', '0.427262 0.634793 0.046088 T T T H\n', '0.408222 0.607427 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.469055 0.603569 0.028149 T T T N\n', '0.446730 0.611334 0.046064 T T T H\n', '0.489762 0.613363 0.046088 T T T H\n', '0.470722 0.585996 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.448221 0.513690 0.028149 T T T N\n', '0.425897 0.521454 0.046064 T T T H\n', '0.468928 0.523483 0.046088 T T T H\n', '0.449889 0.496117 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/14_Zn8Cu5/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [448, 672, 1, 3]
dummy number of surface atoms 1120
mol_coords ['0.489888 0.388690 0.028149 T T T N\n', '0.467564 0.396454 0.046064 T T T H\n', '0.510595 0.398483 0.046088 T T T H\n', '0.491555 0.371117 0.046066 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [448, 672]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [448, 672, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.520833 0.520833 0.381340 T T T N\n', '0.498617 0.528560 0.399254 T T T H\n', '0.541440 0.530579 0.399278 T T T H\n', '0.522493 0.503345 0.399257 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562500 0.562500 0.405361 T T T N\n', '0.540283 0.570227 0.423275 T T T H\n', '0.583107 0.572246 0.423299 T T T H\n', '0.564159 0.545012 0.423278 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.437500 0.479167 0.405361 T T T N\n', '0.415283 0.486893 0.423275 T T T H\n', '0.458107 0.488913 0.423299 T T T H\n', '0.439159 0.461678 0.423278 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.458333 0.500000 0.393350 T T T N\n', '0.436117 0.507727 0.411265 T T T H\n', '0.478940 0.509746 0.411289 T T T H\n', '0.459993 0.482512 0.411267 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.395833 0.520833 0.381340 T T T N\n', '0.373617 0.528560 0.399254 T T T H\n', '0.416440 0.530579 0.399278 T T T H\n', '0.397492 0.503345 0.399257 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.437500 0.493055 0.397354 T T T N\n', '0.415283 0.500782 0.415268 T T T H\n', '0.458107 0.502802 0.415292 T T T H\n', '0.439159 0.475567 0.415271 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/15_ZnCu/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.395833 0.534722 0.389347 T T T N\n', '0.373617 0.542449 0.407261 T T T H\n', '0.416440 0.544468 0.407285 T T T H\n', '0.397492 0.517234 0.407264 T T T H\n']
main_species ['Cu', 'Zn']
main_atom_counts [576, 576]
updated_species ['Cu', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.611194 0.451907 0.319401 T T T N\n', '0.597179 0.456788 0.338129 T T T H\n', '0.620615 0.458063 0.338154 T T T H\n', '0.615819 0.440861 0.338132 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.592640 0.423659 0.349670 T T T N\n', '0.578624 0.428540 0.368398 T T T H\n', '0.602061 0.429815 0.368424 T T T H\n', '0.597265 0.412613 0.368401 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.485167 0.453092 0.331355 T T T N\n', '0.471151 0.457973 0.350084 T T T H\n', '0.494588 0.459248 0.350109 T T T H\n', '0.489792 0.442046 0.350086 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.467293 0.422545 0.358987 T T T N\n', '0.453277 0.427426 0.377715 T T T H\n', '0.476714 0.428701 0.377741 T T T H\n', '0.471918 0.411499 0.377718 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.404966 0.423102 0.354328 T T T N\n', '0.390951 0.427983 0.373057 T T T H\n', '0.414387 0.429258 0.373082 T T T H\n', '0.409591 0.412056 0.373060 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.392897 0.437819 0.345171 T T T N\n', '0.378881 0.442700 0.363900 T T T H\n', '0.402318 0.443975 0.363925 T T T H\n', '0.397521 0.426773 0.363902 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.589847 0.619166 0.325378 T T T N\n', '0.575832 0.624047 0.344106 T T T H\n', '0.599268 0.625322 0.344132 T T T H\n', '0.594472 0.608120 0.344109 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.601917 0.396116 0.334535 T T T N\n', '0.587901 0.400997 0.353264 T T T H\n', '0.611338 0.402272 0.353289 T T T H\n', '0.606542 0.385070 0.353266 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.580570 0.396709 0.340513 T T T N\n', '0.566554 0.401589 0.359241 T T T H\n', '0.589991 0.402865 0.359266 T T T H\n', '0.585195 0.385663 0.359244 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.559563 0.479486 0.345171 T T T N\n', '0.545548 0.484366 0.363900 T T T H\n', '0.568984 0.485641 0.363925 T T T H\n', '0.564188 0.468439 0.363902 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/12_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.539243 0.478893 0.339194 T T T N\n', '0.525228 0.483774 0.357922 T T T H\n', '0.548664 0.485049 0.357947 T T T H\n', '0.543868 0.467847 0.357925 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/13_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.548180 0.452500 0.325378 T T T N\n', '0.534165 0.457380 0.344106 T T T H\n', '0.557601 0.458656 0.344132 T T T H\n', '0.552806 0.441454 0.344109 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/14_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.601917 0.437783 0.334535 T T T N\n', '0.587902 0.442663 0.353264 T T T H\n', '0.611338 0.443939 0.353289 T T T H\n', '0.606542 0.426737 0.353266 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/15_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.613299 0.423102 0.354328 T T T N\n', '0.599284 0.427983 0.373057 T T T H\n', '0.622721 0.429258 0.373082 T T T H\n', '0.617924 0.412056 0.373060 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/17_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.403922 0.433099 0.346671 T T T N\n', '0.389906 0.437980 0.365399 T T T H\n', '0.413343 0.439255 0.365424 T T T H\n', '0.408547 0.422053 0.365402 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/18_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.590778 0.387331 0.333475 T T T N\n', '0.576762 0.392211 0.352204 T T T H\n', '0.600199 0.393486 0.352229 T T T H\n', '0.595403 0.376285 0.352206 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/19_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.590778 0.442886 0.333475 T T T N\n', '0.576762 0.447767 0.352204 T T T H\n', '0.600199 0.449042 0.352229 T T T H\n', '0.595403 0.431840 0.352206 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/21_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.612598 0.404926 0.342686 T T T N\n', '0.598582 0.409806 0.361414 T T T H\n', '0.622019 0.411082 0.361439 T T T H\n', '0.617223 0.393880 0.361417 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/16_ZnPt/5_NH3/22_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [1296, 1296, 1, 3]
dummy number of surface atoms 2592
mol_coords ['0.382329 0.609182 0.336581 T T T N\n', '0.368314 0.614062 0.355309 T T T H\n', '0.391750 0.615337 0.355335 T T T H\n', '0.386954 0.598136 0.355312 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [1296, 1296]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [1296, 1296, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.499609 0.441323 0.384320 T T T N\n', '0.475010 0.452205 0.402234 T T T H\n', '0.510518 0.455048 0.402258 T T T H\n', '0.513354 0.416695 0.402237 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.438515 0.438516 0.386293 T T T N\n', '0.413916 0.449397 0.404207 T T T H\n', '0.449424 0.452240 0.404231 T T T H\n', '0.452260 0.413888 0.404209 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.564919 0.531564 0.385306 T T T N\n', '0.540319 0.542445 0.403220 T T T H\n', '0.575827 0.545289 0.403244 T T T H\n', '0.578663 0.506936 0.403222 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.532966 0.532968 0.384323 T T T N\n', '0.508366 0.543849 0.402237 T T T H\n', '0.543875 0.546692 0.402261 T T T H\n', '0.546711 0.508340 0.402240 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.499606 0.470464 0.384322 T T T N\n', '0.475006 0.481345 0.402236 T T T H\n', '0.510515 0.484189 0.402260 T T T H\n', '0.513351 0.445836 0.402238 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.543149 0.543151 0.384979 T T T N\n', '0.518549 0.554032 0.402893 T T T H\n', '0.554057 0.556875 0.402917 T T T H\n', '0.556893 0.518523 0.402896 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.584814 0.520910 0.384977 T T T N\n', '0.560214 0.531792 0.402891 T T T H\n', '0.595722 0.534635 0.402915 T T T H\n', '0.598558 0.496283 0.402894 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.480179 0.480179 0.384320 T T T N\n', '0.455579 0.491060 0.402234 T T T H\n', '0.491087 0.493904 0.402258 T T T H\n', '0.493923 0.455551 0.402236 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/17_Co3Pt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.521845 0.521846 0.384323 T T T N\n', '0.497245 0.532728 0.402237 T T T H\n', '0.532753 0.535571 0.402261 T T T H\n', '0.535590 0.497219 0.402240 T T T H\n']
main_species ['Co', 'Pt']
main_atom_counts [768, 256]
updated_species ['Co', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.005486 0.510140 0.387615 T T T N\n', '0.992093 0.520763 0.405529 T T T H\n', '0.029534 0.523539 0.405553 T T T H\n', '0.994861 0.486096 0.405532 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.567708 0.572917 0.388505 T T T N\n', '0.554315 0.583540 0.406419 T T T H\n', '0.591757 0.586316 0.406443 T T T H\n', '0.557083 0.548873 0.406421 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.380485 0.416805 0.387615 T T T N\n', '0.367092 0.427428 0.405529 T T T H\n', '0.404534 0.430204 0.405553 T T T H\n', '0.369860 0.392762 0.405532 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.380485 0.604305 0.387615 T T T N\n', '0.367092 0.614928 0.405529 T T T H\n', '0.404534 0.617705 0.405553 T T T H\n', '0.369860 0.580262 0.405532 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.567431 0.479028 0.388060 T T T N\n', '0.554038 0.489652 0.405974 T T T H\n', '0.591480 0.492427 0.405998 T T T H\n', '0.556806 0.454984 0.405977 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.609375 0.406250 0.387615 T T T N\n', '0.595982 0.416873 0.405529 T T T H\n', '0.633424 0.419649 0.405553 T T T H\n', '0.598750 0.382207 0.405532 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.401042 0.614583 0.387615 T T T N\n', '0.387649 0.625206 0.405529 T T T H\n', '0.425090 0.627982 0.405553 T T T H\n', '0.390417 0.590540 0.405532 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.588449 0.489399 0.387911 T T T N\n', '0.575056 0.500022 0.405826 T T T H\n', '0.612498 0.502798 0.405850 T T T H\n', '0.577824 0.465355 0.405828 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/18_Cu3Pt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.484560 0.468842 0.387911 T T T N\n', '0.471167 0.479466 0.405826 T T T H\n', '0.508609 0.482242 0.405850 T T T H\n', '0.473935 0.444799 0.405828 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [768, 256]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.005208 0.510417 0.392294 T T T N\n', '0.992394 0.520582 0.410208 T T T H\n', '0.028219 0.523238 0.410232 T T T H\n', '0.995042 0.487411 0.410211 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.567633 0.510266 0.392619 T T T N\n', '0.554818 0.520431 0.410533 T T T H\n', '0.590644 0.523087 0.410558 T T T H\n', '0.557467 0.487260 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.380284 0.541704 0.392456 T T T N\n', '0.367469 0.551869 0.410371 T T T H\n', '0.403294 0.554525 0.410395 T T T H\n', '0.370117 0.518698 0.410373 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.411496 0.572992 0.392619 T T T N\n', '0.398681 0.583156 0.410533 T T T H\n', '0.434507 0.585813 0.410558 T T T H\n', '0.401330 0.549986 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.598996 0.416629 0.392619 T T T N\n', '0.586181 0.426794 0.410533 T T T H\n', '0.622007 0.429450 0.410558 T T T H\n', '0.588830 0.393623 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.401067 0.552133 0.392511 T T T N\n', '0.388252 0.562298 0.410425 T T T H\n', '0.424078 0.564954 0.410449 T T T H\n', '0.390900 0.529128 0.410428 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.421875 0.593750 0.392619 T T T N\n', '0.409060 0.603915 0.410533 T T T H\n', '0.444886 0.606571 0.410558 T T T H\n', '0.411709 0.570744 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.609400 0.406225 0.392511 T T T N\n', '0.596585 0.416390 0.410425 T T T H\n', '0.632411 0.419046 0.410449 T T T H\n', '0.599234 0.383219 0.410428 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/19_CuPt7/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Cu', 'Pt', 'N', 'H']
dummy counts [128, 896, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.588542 0.552083 0.392619 T T T N\n', '0.575727 0.562248 0.410533 T T T H\n', '0.611553 0.564904 0.410558 T T T H\n', '0.578375 0.529077 0.410536 T T T H\n']
main_species ['Cu', 'Pt']
main_atom_counts [128, 896]
updated_species ['Cu', 'Pt', 'N', 'H']
updated_atom_counts [128, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.999388 0.500000 0.474132 T T T N\n', '0.981966 0.506059 0.496993 T T T H\n', '0.015547 0.507643 0.497024 T T T H\n', '0.000689 0.486286 0.496997 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.624388 0.562500 0.474132 T T T N\n', '0.606966 0.568559 0.496993 T T T H\n', '0.640547 0.570143 0.497024 T T T H\n', '0.625689 0.548786 0.496996 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.593696 0.625000 0.474128 T T T N\n', '0.576274 0.631059 0.496990 T T T H\n', '0.609855 0.632642 0.497020 T T T H\n', '0.594997 0.611286 0.496993 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.593696 0.562500 0.474129 T T T N\n', '0.576274 0.568559 0.496990 T T T H\n', '0.609855 0.570143 0.497021 T T T H\n', '0.594997 0.548786 0.496993 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.406196 0.562500 0.474129 T T T N\n', '0.388774 0.568559 0.496990 T T T H\n', '0.422355 0.570143 0.497021 T T T H\n', '0.407497 0.548786 0.496993 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/20_Fe9Co7/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Co', 'Fe', 'N', 'H']
dummy counts [896, 1152, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.406196 0.500000 0.474129 T T T N\n', '0.388774 0.506059 0.496990 T T T H\n', '0.422355 0.507643 0.497021 T T T H\n', '0.407497 0.486286 0.496994 T T T H\n']
main_species ['Co', 'Fe']
main_atom_counts [896, 1152]
updated_species ['Co', 'Fe', 'N', 'H']
updated_atom_counts [896, 1152, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604158 0.418951 0.384966 T T T N\n', '0.578380 0.426484 0.402880 T T T H\n', '0.628068 0.428452 0.402904 T T T H\n', '0.606083 0.401903 0.402883 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.458324 0.481425 0.384567 T T T N\n', '0.432545 0.488958 0.402481 T T T H\n', '0.482234 0.490926 0.402505 T T T H\n', '0.460249 0.464376 0.402483 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604157 0.543888 0.384162 T T T N\n', '0.578379 0.551420 0.402076 T T T H\n', '0.628068 0.553389 0.402100 T T T H\n', '0.606082 0.526839 0.402078 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.374990 0.606418 0.384570 T T T N\n', '0.349212 0.613951 0.402484 T T T H\n', '0.398901 0.615919 0.402508 T T T H\n', '0.376915 0.589370 0.402486 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.395823 0.585608 0.384975 T T T N\n', '0.370045 0.593141 0.402889 T T T H\n', '0.419734 0.595109 0.402913 T T T H\n', '0.397748 0.568560 0.402891 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.479157 0.488377 0.384703 T T T N\n', '0.453379 0.495909 0.402617 T T T H\n', '0.503067 0.497878 0.402641 T T T H\n', '0.481082 0.471328 0.402620 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604157 0.557795 0.384432 T T T N\n', '0.578379 0.565327 0.402346 T T T H\n', '0.628068 0.567296 0.402371 T T T H\n', '0.606082 0.540746 0.402349 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604157 0.613355 0.384431 T T T N\n', '0.578379 0.620888 0.402345 T T T H\n', '0.628068 0.622856 0.402369 T T T H\n', '0.606082 0.596306 0.402347 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/21_FeNi/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Ni', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.395823 0.599482 0.384705 T T T N\n', '0.370045 0.607014 0.402619 T T T H\n', '0.419734 0.608983 0.402643 T T T H\n', '0.397749 0.582433 0.402622 T T T H\n']
main_species ['Fe', 'Ni']
main_atom_counts [576, 576]
updated_species ['Fe', 'Ni', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.390930 0.562751 0.388532 T T T N\n', '0.366205 0.573688 0.406447 T T T H\n', '0.401894 0.576545 0.406471 T T T H\n', '0.404744 0.538000 0.406449 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.453149 0.500004 0.389545 T T T N\n', '0.428425 0.510940 0.407459 T T T H\n', '0.464113 0.513798 0.407483 T T T H\n', '0.466962 0.475252 0.407462 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.609211 0.437817 0.388536 T T T N\n', '0.584487 0.448753 0.406450 T T T H\n', '0.620176 0.451611 0.406475 T T T H\n', '0.623025 0.413065 0.406453 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.609503 0.468902 0.389044 T T T N\n', '0.584779 0.479838 0.406959 T T T H\n', '0.620467 0.482696 0.406983 T T T H\n', '0.623316 0.444150 0.406961 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.546740 0.593614 0.388527 T T T N\n', '0.522016 0.604550 0.406442 T T T H\n', '0.557704 0.607408 0.406466 T T T H\n', '0.560553 0.568863 0.406444 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.598840 0.458544 0.388872 T T T N\n', '0.574116 0.469480 0.406787 T T T H\n', '0.609804 0.472337 0.406811 T T T H\n', '0.612654 0.433792 0.406789 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.557197 0.604085 0.388857 T T T N\n', '0.532473 0.615021 0.406771 T T T H\n', '0.568161 0.617878 0.406795 T T T H\n', '0.571011 0.579333 0.406774 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.494771 0.416710 0.388532 T T T N\n', '0.470047 0.427646 0.406447 T T T H\n', '0.505735 0.430504 0.406471 T T T H\n', '0.508585 0.391958 0.406449 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/23_Ni3Pt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.536434 0.458363 0.388526 T T T N\n', '0.511710 0.469299 0.406440 T T T H\n', '0.547398 0.472157 0.406464 T T T H\n', '0.550248 0.433612 0.406443 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [768, 256]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.447758 0.385727 0.392216 T T T N\n', '0.424428 0.396046 0.410130 T T T H\n', '0.458103 0.398743 0.410154 T T T H\n', '0.460793 0.362370 0.410132 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.510578 0.541579 0.390743 T T T N\n', '0.487248 0.551899 0.408658 T T T H\n', '0.520924 0.554596 0.408682 T T T H\n', '0.523613 0.518223 0.408660 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.541745 0.541751 0.392175 T T T N\n', '0.518415 0.552070 0.410089 T T T H\n', '0.552090 0.554767 0.410113 T T T H\n', '0.554780 0.518394 0.410092 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.572751 0.479256 0.392188 T T T N\n', '0.549421 0.489576 0.410103 T T T H\n', '0.583097 0.492272 0.410127 T T T H\n', '0.585786 0.455899 0.410105 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.531300 0.531304 0.391220 T T T N\n', '0.507970 0.541624 0.409134 T T T H\n', '0.541646 0.544320 0.409158 T T T H\n', '0.544336 0.507947 0.409137 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.551971 0.489641 0.391229 T T T N\n', '0.528641 0.499961 0.409143 T T T H\n', '0.562316 0.502658 0.409168 T T T H\n', '0.565007 0.466284 0.409146 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.427081 0.552098 0.392171 T T T N\n', '0.403751 0.562417 0.410085 T T T H\n', '0.437426 0.565114 0.410109 T T T H\n', '0.440116 0.528741 0.410088 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/24_NiPt3/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Pt', 'N', 'H']
dummy counts [256, 768, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.593746 0.468756 0.392196 T T T N\n', '0.570416 0.479075 0.410110 T T T H\n', '0.604091 0.481772 0.410134 T T T H\n', '0.606781 0.445399 0.410113 T T T H\n']
main_species ['Ni', 'Pt']
main_atom_counts [256, 768]
updated_species ['Ni', 'Pt', 'N', 'H']
updated_atom_counts [256, 768, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.510417 0.510417 0.409843 T T T N\n', '0.496649 0.517188 0.427011 T T T H\n', '0.523187 0.518958 0.427034 T T T H\n', '0.511445 0.495090 0.427013 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.529090 0.552083 0.408740 T T T N\n', '0.515322 0.558855 0.425908 T T T H\n', '0.541860 0.560625 0.425931 T T T H\n', '0.530118 0.536757 0.425910 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.593750 0.552083 0.408740 T T T N\n', '0.579983 0.558855 0.425908 T T T H\n', '0.606520 0.560625 0.425931 T T T H\n', '0.594778 0.536757 0.425910 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.584414 0.531250 0.409291 T T T N\n', '0.570646 0.538022 0.426459 T T T H\n', '0.597183 0.539791 0.426482 T T T H\n', '0.585442 0.515924 0.426462 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.459414 0.614583 0.409291 T T T N\n', '0.445646 0.621355 0.426459 T T T H\n', '0.472183 0.623125 0.426482 T T T H\n', '0.460442 0.599257 0.426462 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.468750 0.385417 0.408740 T T T N\n', '0.454983 0.392188 0.425908 T T T H\n', '0.481520 0.393958 0.425931 T T T H\n', '0.469778 0.370090 0.425910 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.468750 0.593750 0.409843 T T T N\n', '0.454983 0.600522 0.427011 T T T H\n', '0.481520 0.602291 0.427034 T T T H\n', '0.469778 0.578424 0.427013 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.593750 0.538195 0.409107 T T T N\n', '0.579983 0.544966 0.426276 T T T H\n', '0.606520 0.546736 0.426299 T T T H\n', '0.594778 0.522868 0.426278 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/25_V3Pt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [576, 1728, 1, 3]
dummy number of surface atoms 2304
mol_coords ['0.476415 0.607639 0.409475 T T T N\n', '0.462647 0.614411 0.426643 T T T H\n', '0.489185 0.616180 0.426666 T T T H\n', '0.477442 0.592313 0.426646 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [576, 1728]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [576, 1728, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.585912 0.591658 0.407636 T T T N\n', '0.563506 0.599439 0.424071 T T T H\n', '0.606698 0.601283 0.424093 T T T H\n', '0.587591 0.576429 0.424073 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.375030 0.471577 0.405651 T T T N\n', '0.352625 0.479358 0.422085 T T T H\n', '0.395817 0.481202 0.422107 T T T H\n', '0.376711 0.456349 0.422088 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.551389 0.383539 0.412951 T T T N\n', '0.528984 0.391320 0.429385 T T T H\n', '0.572176 0.393163 0.429407 T T T H\n', '0.553069 0.368310 0.429388 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.457035 0.594122 0.406781 T T T N\n', '0.434629 0.601903 0.423215 T T T H\n', '0.477821 0.603746 0.423238 T T T H\n', '0.458714 0.578893 0.423218 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.474272 0.615063 0.409434 T T T N\n', '0.451867 0.622843 0.425868 T T T H\n', '0.495059 0.624687 0.425891 T T T H\n', '0.475952 0.599834 0.425871 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.431281 0.612553 0.410557 T T T N\n', '0.408876 0.620334 0.426991 T T T H\n', '0.452068 0.622177 0.427014 T T T H\n', '0.432961 0.597324 0.426994 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.499954 0.383516 0.413080 T T T N\n', '0.477549 0.391297 0.429515 T T T H\n', '0.520741 0.393141 0.429537 T T T H\n', '0.501634 0.368287 0.429517 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.519533 0.485078 0.404788 T T T N\n', '0.497127 0.492859 0.421223 T T T H\n', '0.540320 0.494703 0.421245 T T T H\n', '0.521213 0.469850 0.421225 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.499974 0.466617 0.407766 T T T N\n', '0.477569 0.474398 0.424201 T T T H\n', '0.520761 0.476241 0.424223 T T T H\n', '0.501654 0.451388 0.424203 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.375021 0.425084 0.403679 T T T N\n', '0.352616 0.432864 0.420114 T T T H\n', '0.395808 0.434708 0.420136 T T T H\n', '0.376701 0.409855 0.420116 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/12_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.588210 0.427558 0.409301 T T T N\n', '0.565805 0.435339 0.425735 T T T H\n', '0.608997 0.437183 0.425757 T T T H\n', '0.589890 0.412329 0.425738 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/13_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.588201 0.381064 0.407329 T T T N\n', '0.565795 0.388845 0.423764 T T T H\n', '0.608987 0.390688 0.423786 T T T H\n', '0.589881 0.365835 0.423766 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/14_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.506143 0.425090 0.410292 T T T N\n', '0.483738 0.432871 0.426726 T T T H\n', '0.526930 0.434714 0.426748 T T T H\n', '0.507823 0.409861 0.426729 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/15_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.579744 0.550059 0.410376 T T T N\n', '0.557339 0.557840 0.426811 T T T H\n', '0.600531 0.559683 0.426833 T T T H\n', '0.581424 0.534830 0.426813 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/16_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.454196 0.607246 0.408924 T T T N\n', '0.431790 0.615027 0.425358 T T T H\n', '0.474983 0.616870 0.425381 T T T H\n', '0.455876 0.592017 0.425361 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/17_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.499978 0.621221 0.410606 T T T N\n', '0.477572 0.629002 0.427041 T T T H\n', '0.520765 0.630846 0.427063 T T T H\n', '0.501658 0.605993 0.427043 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/18_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.499987 0.478933 0.405736 T T T N\n', '0.477582 0.486713 0.422171 T T T H\n', '0.520774 0.488557 0.422193 T T T H\n', '0.501667 0.463704 0.422173 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/19_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.600477 0.411235 0.406770 T T T N\n', '0.578072 0.419016 0.423204 T T T H\n', '0.621264 0.420859 0.423226 T T T H\n', '0.602157 0.396006 0.423207 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/20_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.412525 0.617898 0.407607 T T T N\n', '0.390119 0.625679 0.424042 T T T H\n', '0.433312 0.627523 0.424064 T T T H\n', '0.414205 0.602670 0.424044 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/21_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.611942 0.536210 0.411205 T T T N\n', '0.589536 0.543990 0.427639 T T T H\n', '0.632728 0.545834 0.427661 T T T H\n', '0.613622 0.520981 0.427641 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/27_VPt8/5_NH3/22_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'V', 'N', 'H']
dummy counts [1184, 160, 1, 3]
dummy number of surface atoms 1344
mol_coords ['0.446802 0.565585 0.408808 T T T N\n', '0.424396 0.573366 0.425242 T T T H\n', '0.467588 0.575210 0.425264 T T T H\n', '0.448482 0.550357 0.425245 T T T H\n']
main_species ['Pt', 'V']
main_atom_counts [1184, 160]
updated_species ['Pt', 'V', 'N', 'H']
updated_atom_counts [1184, 160, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.471442 0.591237 0.315203 T T T N\n', '0.449291 0.598941 0.333932 T T T H\n', '0.491989 0.600954 0.333957 T T T H\n', '0.473097 0.573800 0.333934 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.571118 0.513315 0.310260 T T T N\n', '0.548967 0.521019 0.328989 T T T H\n', '0.591664 0.523032 0.329014 T T T H\n', '0.572772 0.495878 0.328991 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.450926 0.543725 0.321747 T T T N\n', '0.428775 0.551429 0.340475 T T T H\n', '0.471472 0.553442 0.340501 T T T H\n', '0.452580 0.526288 0.340478 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.504984 0.513315 0.347956 T T T N\n', '0.482833 0.521019 0.366685 T T T H\n', '0.525530 0.523032 0.366710 T T T H\n', '0.506638 0.495878 0.366687 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.613213 0.427276 0.331579 T T T N\n', '0.591062 0.434980 0.350308 T T T H\n', '0.633760 0.436993 0.350333 T T T H\n', '0.614868 0.409839 0.350311 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.425713 0.411853 0.331579 T T T N\n', '0.403562 0.419558 0.350308 T T T H\n', '0.446260 0.421571 0.350333 T T T H\n', '0.427368 0.394417 0.350311 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.408942 0.450815 0.315203 T T T N\n', '0.386791 0.458519 0.333932 T T T H\n', '0.429489 0.460532 0.333957 T T T H\n', '0.410597 0.433378 0.333934 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.602955 0.403520 0.334851 T T T N\n', '0.580804 0.411224 0.353580 T T T H\n', '0.623501 0.413237 0.353605 T T T H\n', '0.604610 0.386083 0.353583 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.586184 0.442481 0.318475 T T T N\n', '0.564033 0.450185 0.337204 T T T H\n', '0.606730 0.452198 0.337229 T T T H\n', '0.587839 0.425044 0.337206 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.523684 0.427059 0.318475 T T T N\n', '0.501533 0.434762 0.337204 T T T H\n', '0.544231 0.436776 0.337229 T T T H\n', '0.525339 0.409622 0.337206 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.386022 0.498110 0.316003 T T T N\n', '0.363871 0.505814 0.334732 T T T H\n', '0.406568 0.507827 0.334757 T T T H\n', '0.387677 0.480673 0.334735 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/12_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.583780 0.489776 0.312732 T T T N\n', '0.561629 0.497480 0.331460 T T T H\n', '0.604326 0.499493 0.331485 T T T H\n', '0.585435 0.472339 0.331463 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/13_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.450926 0.513315 0.321747 T T T N\n', '0.428775 0.521019 0.340475 T T T H\n', '0.471472 0.523032 0.340501 T T T H\n', '0.452580 0.495878 0.340478 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/14_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.413051 0.388315 0.329108 T T T N\n', '0.390900 0.396019 0.347837 T T T H\n', '0.433597 0.398032 0.347862 T T T H\n', '0.414705 0.370878 0.347839 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/15_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.399290 0.429982 0.326121 T T T N\n', '0.377138 0.437686 0.344849 T T T H\n', '0.419836 0.439699 0.344875 T T T H\n', '0.400944 0.412545 0.344852 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/16_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.407657 0.513315 0.317918 T T T N\n', '0.385506 0.521019 0.336646 T T T H\n', '0.428203 0.523032 0.336672 T T T H\n', '0.409311 0.495878 0.336649 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/28_Zn11Ni2/5_NH3/17_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [128, 736, 1, 3]
dummy number of surface atoms 864
mol_coords ['0.468945 0.513315 0.330483 T T T N\n', '0.446794 0.521019 0.349212 T T T H\n', '0.489492 0.523032 0.349237 T T T H\n', '0.470600 0.495878 0.349214 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [128, 736]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [128, 736, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.515625 0.503222 0.351679 T T T N\n', '0.497018 0.508221 0.370408 T T T H\n', '0.532883 0.509527 0.370433 T T T H\n', '0.517014 0.491908 0.370410 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.578125 0.504769 0.369512 T T T N\n', '0.559518 0.509769 0.388240 T T T H\n', '0.595383 0.511075 0.388266 T T T H\n', '0.579515 0.493455 0.388243 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.546591 0.534953 0.365284 T T T N\n', '0.527984 0.539952 0.384013 T T T H\n', '0.563849 0.541258 0.384038 T T T H\n', '0.547980 0.523639 0.384016 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.562358 0.582361 0.367398 T T T N\n', '0.543751 0.587360 0.386127 T T T H\n', '0.579616 0.588667 0.386152 T T T H\n', '0.563747 0.571047 0.386129 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.531108 0.581588 0.358482 T T T N\n', '0.512501 0.586587 0.377210 T T T H\n', '0.548366 0.587893 0.377236 T T T H\n', '0.532497 0.570273 0.377213 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.546875 0.566496 0.360595 T T T N\n', '0.528268 0.571495 0.379324 T T T H\n', '0.564133 0.572801 0.379349 T T T H\n', '0.548264 0.555181 0.379327 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.562358 0.613611 0.367398 T T T N\n', '0.543751 0.618610 0.386127 T T T H\n', '0.579616 0.619917 0.386152 T T T H\n', '0.563747 0.602297 0.386129 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.578125 0.597453 0.365284 T T T N\n', '0.559518 0.602452 0.384013 T T T H\n', '0.595383 0.603758 0.384038 T T T H\n', '0.579515 0.586139 0.384016 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.390625 0.534953 0.365284 T T T N\n', '0.372018 0.539952 0.384013 T T T H\n', '0.407883 0.541258 0.384038 T T T H\n', '0.392014 0.523639 0.384016 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.406108 0.425337 0.358482 T T T N\n', '0.387501 0.430336 0.377210 T T T H\n', '0.423366 0.431643 0.377236 T T T H\n', '0.407498 0.414023 0.377213 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.546780 0.576815 0.362158 T T T N\n', '0.528174 0.581814 0.380887 T T T H\n', '0.564038 0.583120 0.380912 T T T H\n', '0.548170 0.565501 0.380890 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/12_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.578125 0.608225 0.366694 T T T N\n', '0.559518 0.613224 0.385422 T T T H\n', '0.595383 0.614531 0.385447 T T T H\n', '0.579515 0.596911 0.385425 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/13_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.578125 0.587392 0.366694 T T T N\n', '0.559518 0.592391 0.385422 T T T H\n', '0.595383 0.593697 0.385447 T T T H\n', '0.579515 0.576078 0.385425 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/14_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.390625 0.524376 0.360749 T T T N\n', '0.372018 0.529375 0.379478 T T T H\n', '0.407883 0.530682 0.379503 T T T H\n', '0.392014 0.513062 0.379481 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/15_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.421780 0.430981 0.362158 T T T N\n', '0.403174 0.435980 0.380887 T T T H\n', '0.439038 0.437287 0.380912 T T T H\n', '0.423170 0.419667 0.380890 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/31_Zn3Pt/5_NH3/16_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [512, 1536, 1, 3]
dummy number of surface atoms 2048
mol_coords ['0.390625 0.420210 0.360749 T T T N\n', '0.372018 0.425208 0.379478 T T T H\n', '0.407883 0.426515 0.379503 T T T H\n', '0.392014 0.408895 0.379481 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [512, 1536]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [512, 1536, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.576229 0.534388 0.422907 T T T N\n', '0.554029 0.542108 0.439388 T T T H\n', '0.596820 0.544126 0.439411 T T T H\n', '0.577886 0.516912 0.439391 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.509857 0.502796 0.430831 T T T N\n', '0.487656 0.510517 0.447312 T T T H\n', '0.530448 0.512535 0.447334 T T T H\n', '0.511514 0.485321 0.447314 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.447356 0.596888 0.430831 T T T N\n', '0.425156 0.604608 0.447312 T T T H\n', '0.467948 0.606626 0.447334 T T T H\n', '0.449014 0.579412 0.447314 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.480543 0.612683 0.426869 T T T N\n', '0.458342 0.620405 0.443350 T T T H\n', '0.501134 0.622422 0.443372 T T T H\n', '0.482200 0.595208 0.443352 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.418043 0.393592 0.426869 T T T N\n', '0.395843 0.401313 0.443350 T T T H\n', '0.438634 0.403330 0.443372 T T T H\n', '0.419700 0.376117 0.443352 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.418043 0.518592 0.426869 T T T N\n', '0.395843 0.526313 0.443350 T T T H\n', '0.438634 0.528330 0.443372 T T T H\n', '0.419700 0.501117 0.443352 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.509857 0.534388 0.430831 T T T N\n', '0.487656 0.542108 0.447312 T T T H\n', '0.530448 0.544126 0.447334 T T T H\n', '0.511514 0.516912 0.447314 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.448647 0.617721 0.428190 T T T N\n', '0.426447 0.625442 0.444671 T T T H\n', '0.469238 0.627460 0.444693 T T T H\n', '0.450305 0.600246 0.444673 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.406981 0.492721 0.428190 T T T N\n', '0.384781 0.500442 0.444671 T T T H\n', '0.427572 0.502460 0.444693 T T T H\n', '0.408638 0.475246 0.444673 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.448647 0.534388 0.428190 T T T N\n', '0.426447 0.542108 0.444671 T T T H\n', '0.469238 0.544126 0.444693 T T T H\n', '0.450305 0.516912 0.444673 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/32_Zn9Fe4/5_NH3/11_ad_site/POSCAR_initial_cent441
dummy species ['Fe', 'Zn', 'N', 'H']
dummy counts [320, 896, 1, 3]
dummy number of surface atoms 1216
mol_coords ['0.531981 0.534388 0.428190 T T T N\n', '0.509780 0.542108 0.444671 T T T H\n', '0.552572 0.544126 0.444693 T T T H\n', '0.533638 0.516912 0.444673 T T T H\n']
main_species ['Fe', 'Zn']
main_atom_counts [320, 896]
updated_species ['Fe', 'Zn', 'N', 'H']
updated_atom_counts [320, 896, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.520833 0.494037 0.350732 T T T N\n', '0.496708 0.501681 0.369460 T T T H\n', '0.543211 0.503678 0.369485 T T T H\n', '0.522635 0.476738 0.369463 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/2_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562500 0.535690 0.369471 T T T N\n', '0.538375 0.543334 0.388200 T T T H\n', '0.584877 0.545331 0.388225 T T T H\n', '0.564302 0.518391 0.388203 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.375000 0.473197 0.360102 T T T N\n', '0.350875 0.480841 0.378830 T T T H\n', '0.397377 0.482838 0.378855 T T T H\n', '0.376802 0.455898 0.378833 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604167 0.452357 0.369471 T T T N\n', '0.580041 0.460001 0.388200 T T T H\n', '0.626544 0.461998 0.388225 T T T H\n', '0.605968 0.435058 0.388203 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.583333 0.431530 0.360102 T T T N\n', '0.559208 0.439174 0.378830 T T T H\n', '0.605710 0.441171 0.378855 T T T H\n', '0.585135 0.414231 0.378833 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.479167 0.577371 0.350732 T T T N\n', '0.455041 0.585014 0.369460 T T T H\n', '0.501544 0.587012 0.369485 T T T H\n', '0.480968 0.560072 0.369463 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]

Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604167 0.466250 0.363225 T T T N\n', '0.580041 0.473894 0.381953 T T T H\n', '0.626544 0.475891 0.381979 T T T H\n', '0.605968 0.448951 0.381956 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.604167 0.438473 0.363225 T T T N\n', '0.580041 0.446116 0.381953 T T T H\n', '0.626544 0.448113 0.381979 T T T H\n', '0.605968 0.421174 0.381956 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.479167 0.591255 0.356978 T T T N\n', '0.455041 0.598899 0.375707 T T T H\n', '0.501544 0.600896 0.375732 T T T H\n', '0.480968 0.573956 0.375709 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/33_ZnNi/5_NH3/10_ad_site/POSCAR_initial_cent441
dummy species ['Ni', 'Zn', 'N', 'H']
dummy counts [576, 576, 1, 3]
dummy number of surface atoms 1152
mol_coords ['0.562500 0.563478 0.356978 T T T N\n', '0.538375 0.571121 0.375707 T T T H\n', '0.584877 0.573118 0.375732 T T T H\n', '0.564302 0.546178 0.375709 T T T H\n']
main_species ['Ni', 'Zn']
main_atom_counts [576, 576]
updated_species ['Ni', 'Zn', 'N', 'H']
updated_atom_counts [576, 576, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/1_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.005733 0.510679 0.389275 T T T N\n', '0.992916 0.520845 0.407189 T T T H\n', '0.028747 0.523502 0.407213 T T T H\n', '0.995564 0.487669 0.407192 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/3_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.380470 0.604298 0.394679 T T T N\n', '0.367653 0.614464 0.412593 T T T H\n', '0.403485 0.617121 0.412617 T T T H\n', '0.370303 0.581288 0.412595 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/4_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.411589 0.385679 0.389275 T T T N\n', '0.398772 0.395845 0.407189 T T T H\n', '0.434604 0.398502 0.407213 T T T H\n', '0.401421 0.362669 0.407192 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/5_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.599089 0.604036 0.389275 T T T N\n', '0.586272 0.614202 0.407189 T T T H\n', '0.622104 0.616859 0.407213 T T T H\n', '0.588921 0.581026 0.407192 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/6_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.401129 0.614758 0.392877 T T T N\n', '0.388312 0.624924 0.410792 T T T H\n', '0.424144 0.627581 0.410816 T T T H\n', '0.390961 0.591749 0.410794 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/7_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.609463 0.593662 0.392877 T T T N\n', '0.596645 0.603829 0.410792 T T T H\n', '0.632477 0.606486 0.410816 T T T H\n', '0.599294 0.570653 0.410794 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/8_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.546875 0.531250 0.389275 T T T N\n', '0.534058 0.541416 0.407189 T T T H\n', '0.569889 0.544073 0.407213 T T T H\n', '0.536707 0.508240 0.407192 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]
Central molecule saved to /home/parastoo/Desktop/ML_project/analysis/ML_project/transferred_files/Subhmoy/34_ZnPt3/5_NH3/9_ad_site/POSCAR_initial_cent441
dummy species ['Pt', 'Zn', 'N', 'H']
dummy counts [768, 256, 1, 3]
dummy number of surface atoms 1024
mol_coords ['0.463542 0.614583 0.389275 T T T N\n', '0.450725 0.624750 0.407189 T T T H\n', '0.486556 0.627406 0.407213 T T T H\n', '0.453374 0.591574 0.407192 T T T H\n']
main_species ['Pt', 'Zn']
main_atom_counts [768, 256]
updated_species ['Pt', 'Zn', 'N', 'H']
updated_atom_counts [768, 256, 1, 3]